### ISSUE TITLE
CLI upload error

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#100]
Hey I was trying to use official CLI from peertube but got error exactly same like this guy https://github.com/Chocobozzz/PeerTube/issues/1882 so maybe you can make special install like and you did with peertube so its will be easer to use it

**Comment by yalh76** [comment]
It seems to be an issue in the upstream application Peertube, so maybe we can wait a response for this issue.

There is already a special installation for [OVH](https://github.com/YunoHost-Apps/peertube_ynh/tree/ovh_fix) that don't install nodejs automatically
