### ISSUE TITLE
Dissable download direct link

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#101]
Hey in new realise they done that thing we can dissable download button  but anyway if some know where and how to add words like that https://link.net/download/videos/baf8b439-4302-4abb-bd9a-cb9df2c6384b-304.mp4 i mean download/videos... And in to the end 304.mp4 so they can use best download speed like they can so if possibe where I have to config something to disable that download? Because best if they will use webssed links its given just 1mbps no more so cheers if possible to do something

**Comment by yalh76** [comment]
Hi @filmaidykai 

Better to ask your question on peertube repository.
