### ISSUE TITLE
Blacklist the referer in nginx.

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#102]
I found a lesson  https://gist.github.com/Belphemur/ca91335c3870d9351b41so wanna ask possible to integrate somewhere in peertube?  And its help to disable hotlink stream for some specific web pages? Or maybe is possible to block specific address with yunohost if yes how I have to do that thanks

**Comment by yalh76** [comment]
Hi @filmaidykai 

Your link doesn't work.

And we don't do modification on upstream applications, only package them to be available on yunohost. Maybe your question is more accurate on peertube repository
