### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#103]
hey just simple question how you know if u using that link for download for example https://peertube.ptx/download/videos/video-720.mp4 so its given unlimited download when you trying download file with webseed link its given 1mbps so just wanna ask maybe you know where I have to change seeting for download/video... and make from unlimited to same like webseed 

cheers

**Comment by yalh76** [comment]
I don't completly understand your question. 
Have you checked the [documentation ](https://docs.joinpeertube.org/) or [upstream app issues](https://github.com/Chocobozzz/PeerTube/issues?utf8=%E2%9C%93&q=download+limit) ?
