### ISSUE TITLE
Error 502 after upgrade (on ovh-fix)

### ISSUE THREAD

**Issue by raphgilles** [YunoHost-Apps/peertube_ynh#107]
Hello,

I get an error 502 when I try to upgrade to the 1.3.1 on the ovh-fix branch.

During the upgrade process, when I do `cd /var/www/peertube && sudo yarn install --production --pure-lockfile` it give me this : 

```
/usr/share/yarn/lib/cli.js:45703
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Have you an idea here about what is happening ?

Thank you :)

**Comment by yalh76** [comment]
Hi @raphgilles 

No idea for now.
Package_check is ok, it's also testing the upgrade from 1.2.1 and it's working
https://ci-apps.yunohost.org/ci/job/3968.
I will test automatic upgrade from 1.3.0

**Comment by yalh76** [comment]
I found it. The error come from node that is not found...

if you execute 
```
PATH=$PATH:/opt/node_n/bin/
cd /var/www/peertube && sudo yarn install --production --pure-lockfile
```

It must work...

**Comment by raphgilles** [comment]
I have exactly the same error.

I changed nothing to the original installation, so I don't know what it could be.

**Comment by yalh76** [comment]
and I you do:
```
su
PATH=$PATH:/opt/node_n/bin/
cd /var/www/peertube && yarn install --production --pure-lockfile
```

**Comment by raphgilles** [comment]
Same error too.

**Comment by raphgilles** [comment]
Oh sorry. I missed these errors after `su` : 
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

And after `/var/www/peertube# cd /var/www/peertube && yarn install --production --pure-lockfile` : 
`chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

And the error of the issue after that.

**Comment by yalh76** [comment]
and if you do:
```
cd /var/www/peertube 
su
PATH=$PATH:/opt/node_n/bin/
yarn install --production --pure-lockfile
```

**Comment by raphgilles** [comment]
I tried, but no.

**Comment by yalh76** [comment]
OK, I don't know what is specific on your yunohost.

The error you have is because the user that execute yarn don't have nodejs in his path.

So, I you give more informations or try by you side...

**Comment by yalh76** [comment]
if you do:
`yarn --version` or `sudo yarn --version`  you still have an error ?

**Comment by raphgilles** [comment]
OK.

So I tried `yarn --version` to obtain the same error.

I updated nodejs with `sudo n latest` (All the other methods I found did not work.)

Now I have this : 

> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/var/www/peertube/node_modules/sharp/build'
>   TOUCH Release/obj.target/libvips-cpp.stamp
>   CXX(target) Release/obj.target/sharp/src/common.o
> In file included from ../src/common.cc:27:0:
> ../src/common.h:80:16: error: ‘Handle’ is not a member of ‘v8’
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>                 ^~
> ../src/common.h:80:37: error: expected primary-expression before ‘>’ token
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>                                      ^
> ../src/common.h:80:39: error: ‘obj’ was not declared in this scope
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>                                        ^~~
> ../src/common.h:80:56: error: expected primary-expression before ‘attr’
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>                                                         ^~~~
> ../src/common.h:80:60: error: expression list treated as compound expression in initializer [-fpermissive]
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>                                                             ^
> ../src/common.h:81:25: error: ‘Handle’ is not a member of ‘v8’
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
>                          ^~
> ../src/common.h:81:46: error: expected primary-expression before ‘>’ token
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
>                                               ^
> ../src/common.h:81:48: error: ‘obj’ was not declared in this scope
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
>                                                 ^~~
> ../src/common.h:81:65: error: expected primary-expression before ‘attr’
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
>                                                                  ^~~~
> ../src/common.h:82:34: error: ‘Handle’ is not a member of ‘v8’
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
>                                   ^~
> ../src/common.h:82:55: error: expected primary-expression before ‘>’ token
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
>                                                        ^
> ../src/common.h:82:57: error: ‘obj’ was not declared in this scope
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
>                                                          ^~~
> ../src/common.h:82:74: error: expected primary-expression before ‘attr’
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
>                                                                           ^~~~
> ../src/common.h:83:44: error: ‘Handle’ is not a member of ‘v8’
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                             ^~
> ../src/common.h:83:65: error: expected primary-expression before ‘>’ token
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                  ^
> ../src/common.h:83:67: error: ‘obj’ was not declared in this scope
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                    ^~~
> ../src/common.h:83:84: error: expected primary-expression before ‘attr’
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                                     ^~~~
> ../src/common.h:83:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                      ^~~~~~
> ../src/common.h:83:90: error: expected ‘;’ before ‘{’ token
>    template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                                           ^
> ../src/common.h:86:33: error: ‘Handle’ is not a member of ‘v8’
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                                  ^~
> ../src/common.h:86:54: error: expected primary-expression before ‘>’ token
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                                                       ^
> ../src/common.h:86:56: error: ‘obj’ was not declared in this scope
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                                                         ^~~
> ../src/common.h:86:73: error: expected primary-expression before ‘attr’
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                          ^~~~
> ../src/common.h:86:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                           ^~~~~~
> ../src/common.h:86:79: error: expected ‘;’ before ‘{’ token
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                                ^
> ../src/common.h:89:33: error: ‘Handle’ is not a member of ‘v8’
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
>                                  ^~
> ../src/common.h:89:54: error: expected primary-expression before ‘>’ token
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
>                                                       ^
> ../src/common.h:89:56: error: ‘obj’ was not declared in this scope
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
>                                                         ^~~
> ../src/common.h:89:61: error: expected primary-expression before ‘int’
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
>                                                              ^~~
> ../src/common.h:86:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
>                           ^~~~~~
> ../src/common.h:89:71: error: expected ‘;’ before ‘{’ token
>    template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
>                                                                        ^
> ../src/common.h:95:5: error: ‘Handle’ is not a member of ‘v8’
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>      ^~
> ../src/common.h:95:26: error: expected primary-expression before ‘>’ token
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>                           ^
> ../src/common.h:95:28: error: ‘input’ was not declared in this scope
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>                             ^~~~~
> ../src/common.h:95:70: error: expected primary-expression before ‘&’ token
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>                                                                       ^
> ../src/common.h:95:71: error: ‘buffersToPersist’ was not declared in this scope
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>                                                                        ^~~~~~~~~~~~~~~~
> ../src/common.h:95:87: error: expression list treated as compound expression in initializer [-fpermissive]
>      v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
>                                                                                        ^
> ../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
>                     ^~~~~~
> In file included from ../src/common.cc:27:0:
> ../src/common.h:80:8: note: ‘bool sharp::HasAttr’ previously defined here
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
>         ^~~~~~~
> ../src/common.cc:34:16: error: ‘Handle’ is not a member of ‘v8’
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
>                 ^~
> ../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
>                                      ^
> ../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
>                                        ^~~
> ../src/common.cc:34:56: error: expected primary-expression before ‘attr’
>    bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
>                                                         ^~~~
> ../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
>                              ^~~~~~
> In file included from ../src/common.cc:27:0:
> ../src/common.h:81:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
>                ^~~~~~~~~
> ../src/common.cc:37:25: error: ‘Handle’ is not a member of ‘v8’
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
>                          ^~
> ../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
>                                               ^
> ../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
>                                                 ^~~
> ../src/common.cc:37:65: error: expected primary-expression before ‘attr’
>    std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                  ^~~~
> ../src/common.cc:40:38: error: redefinition of ‘std::vector<double> sharp::AttrAsRgba’
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
>                                       ^~~~~~
> In file included from ../src/common.cc:27:0:
> ../src/common.h:82:23: note: ‘std::vector<double> sharp::AttrAsRgba’ previously declared here
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
>                        ^~~~~~~~~~
> ../src/common.cc:40:34: error: ‘Handle’ is not a member of ‘v8’
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
>                                   ^~
> ../src/common.cc:40:55: error: expected primary-expression before ‘>’ token
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
>                                                        ^
> ../src/common.cc:40:57: error: ‘obj’ was not declared in this scope
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
>                                                          ^~~
> ../src/common.cc:40:74: error: expected primary-expression before ‘attr’
>    std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
>                                                                           ^~~~
> ../src/common.cc:669:1: error: expected ‘}’ at end of input
>  }  // namespace sharp
>  ^
> cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
> sharp.target.mk:134: recipe for target 'Release/obj.target/sharp/src/common.o' failed
> make: Leaving directory '/var/www/peertube/node_modules/sharp/build'
> make: *** [Release/obj.target/sharp/src/common.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> gyp ERR! System Linux 4.9.179-xxxx-std-ipv6-64
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /var/www/peertube/node_modules/sharp

**Comment by yalh76** [comment]
So if your had the same error with `yarn --version`, it's because node wasn't available in the PATH

Not sure that doing `sudo n latest` was a good idea. you need to roll back that action.

**Comment by raphgilles** [comment]
But I don't understand. Node is this path.

![node](https://user-images.githubusercontent.com/49836486/59724845-b1751480-922b-11e9-92c7-dd38bd20242b.JPG)

**Comment by yalh76** [comment]
if you execute `node --version` what's the result ?

**Comment by yalh76** [comment]
When I say PATH it's https://www.commentcamarche.net/faq/3585-bash-la-variable-d-environnement-path
or https://wiki.debian.org/EnvironmentVariables
It's where DEBIAN will search for commands

**Comment by raphgilles** [comment]
I actually have the `v10.16.0` of node installed.

and `yarn --version` give me `1.16.0` now I downgraded to the stable.

**Comment by yalh76** [comment]
As now `yarn --version` works you can do the upgrade of peertube but note sure it will work with nodejs 10.16

**Comment by raphgilles** [comment]
OK. It was a pretty apocalyptic method but after the upgrade to the latest version and the downgrade to the stable version of yarn, `cd /var/www/peertube && yarn install --production --pure-lockfile` worked.

And my instance is up to date !

Thank you a lot for your help, you are very patient with me.

**Comment by yalh76** [comment]
As I said, all the time it was a PATH issue for nodejs.
I think I will update the readme for ovh_fix
