### ISSUE TITLE
I have a corrupted source error

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/peertube_ynh#11]
Hello

I just tried Peerube on my Yunohost and I have a corrupted source error. Mastodon is already installed on the server

Thank you for your help

Bonjour

Je viens d'essayé d'installer Peertube sur mon Yunohost et j'ai une erreur de source corrompu. Mastodon est déjà installé sur le serveur

Merci de votre aide

![peertube-echec-installation](https://user-images.githubusercontent.com/35960036/37969081-33620be6-31d0-11e8-9d37-c3b998d4ac9c.png)

**Comment by anmol26s** [comment]
Sorry for inconvenience. You can try the testing branch for now. 
https://github.com/YunoHost-Apps/peertube_ynh/tree/testing

**Comment by lesamarien** [comment]
It's exactly the same problem and the same installation link. With this installation error, I no longer have access to Yunohost

C'est exactement le même problème et le même lien d'installation. Avec cette erreur d'installation, je n'ai plus accès à Yunohost

**Comment by anmol26s** [comment]
The testing branch have different source then then the testing branch. 
Your source from the image I see is from the master branch.
Can you show the log from the testing branch?

**Comment by lesamarien** [comment]
Here is the link found in the Testing branch: sudo yunohost https://github.com/YunoHost-Apps/peertube_ynh

Voici lien que l'on trouve dans la branche Testing : sudo yunohost https://github.com/YunoHost-Apps/peertube_ynh

**Comment by lesamarien** [comment]
The installation command of the Testing branch is the same as the main one

La commande d'installation de la branche Testing est la même que la principale

**Comment by anmol26s** [comment]
Can you install with this command:
`yunohost app install  --verbose https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`

Thanks

**Comment by lesamarien** [comment]
I have gone further with this installation but that gives a setup failure again. Unfortunately, that broke my instance of Mastodon. I attach you the file of the installation procedure in .txt

J'ai été plus loin avec cette installation mais qui donne un echec d'installation encore. Malheureusement, cela a cassé mon instance de Mastodon. Je vous joint le fichier de la procedure d'installation en .txt
[install-peertube.txt](https://github.com/YunoHost-Apps/peertube_ynh/files/1852439/install-peertube.txt)

**Comment by anmol26s** [comment]
Ok. Can you try password without the bracket `(` or special character ? You can try simple password and change it from admin interface later.

**Comment by anmol26s** [comment]
Mastodon package don't have stored dependencies I guess. Peertube might have removed them on fail.
You can install it manually 
`sudo apt-get install imagemagick libpq-dev libxml2-dev libxslt1-dev file curl apt-transport-https pkg-config libprotobuf-dev protobuf-compiler libicu-dev libidn11-dev redis-server redis-tools postgresql postgresql-contrib postgresql-server-dev-9.4 autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
`

**Comment by lesamarien** [comment]
J'ai changé le mot de passe mais ça fait maintenant 20 minutes que c'est bloqué ici : 

I changed the password but it's been 20 minutes since it's blocked here:

Attention : (node:6728) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: la relation « user » n'existe pas
Attention :     at Query.formatError (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
Attention :     at query.catch.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
Attention :     at tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)
Attention :     at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:512:31)
Attention :     at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:569:18)
Attention :     at Promise._settlePromise0 (/var/www/peertube/node_modules/bluebird/js/release/promise.js:614:10)
Attention :     at Promise._settlePromises (/var/www/peertube/node_modules/bluebird/js/release/promise.js:689:18)
Attention :     at Async._drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:133:16)
Attention :     at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:143:10)
Attention :     at Immediate.Async.drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:17:14)
Attention :     at runCallback (timers.js:794:20)
Attention :     at tryOnImmediate (timers.js:752:5)
Attention :     at processImmediate [as _immediateCallback] (timers.js:729:5)
Attention : (node:6728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Attention : (node:6728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by anmol26s** [comment]
How did you changed your password? Was the installation successful?

**Comment by lesamarien** [comment]
I put a simple password without special characters and the installation was not successful. Another failure at the end of the installation

J'ai mis un mot de passe simple sans caractères spéciaux et l'installation n'a pas réussi. Encore un echec à la fin de l'installation

**Comment by anmol26s** [comment]
It looks a format error. What password you entered? 
Is you postgresql running ? See by  `service postgresql status`
You can upgrade the mastodon package, it should fix it.

**Comment by lesamarien** [comment]
Hello

I entered a password just with letters and numbers. I use Postegrsql and its status is active. For mastodon, I had to uninstall it completely and reinstall it.

Bonjour

J'ai entré un mot de passe juste avec des lettres et des chiffres. J'utilise Postegrsql et son statut est actif. Pour mastodon, j'ai du le desinstaller entierement et le réinstaller.

**Comment by anmol26s** [comment]
Password comes to your email now and you can change it after login to the app.

**Comment by anmol26s** [comment]
This should be solved now. If you face the issue again please re-open issue.
