### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#110]
Hey after 7 month yesterday I just make activation for Signup requires email verification so I just use couple of emails for test one from yahoo second from gmail so I make registration and I dont know where is a problem why system dont send verification email any idea?

**Comment by yalh76** [comment]
Hi @filmaidykai 

Just tested the verification email for user registration and it's working. Registered a user with @yahoo.com email and received it in the spam.

Maybe it comes from your yunohost. You have to check the logs.

**Comment by filmaidykai** [comment]
Try with my instance https://hostyour.tv/ I dont think you will get email

**Comment by yalh76** [comment]
I trust you that mails are not send.

The point is with yunohost standard installation + peertube_ynh : email verifications are sent out. So seems specific to your installation.

So you have to check the peertube logs doing `journalctl -u peertube -fe` and trying to register a user with email verification to see if peertube was able to send mail to postfix?

Have you checked if there are mails in the postfix queue ? doing `mailq`

**Comment by filmaidykai** [comment]
what that mean? and possible to fix it?

A8A161E4F9F77      590 Tue Jun 18 06:36:01  root@hostyour.tv
(delivery temporarily suspended: connect to ziuri.me[2606:4700:31::681f:2bf]:25: Connection timed out)
                                         admin@ziuri.me

A40031E4FA00A      590 Wed Jun 19 15:02:02  root@hostyour.tv
(delivery temporarily suspended: connect to ziuri.me[104.31.3.1**]:25: Connection timed out)
                                         admin@ziuri.me

A78E21E4F894F     2582 Sun Jun 16 06:32:32  MAILER-DAEMON
(delivery temporarily suspended: connect to ziuri.me[104.31.3.1**]:25: Connection timed out)
                                         admin@ziuri.me

A52BC1E4FA3DF      590 Sun Jun 16 07:12:01  root@hostyour.tv
(delivery temporarily suspended: connect to ziuri.me[104.31.2.1**]:25: Connection timed out)
                                         admin@ziuri.me

AF0EE1E4F8D50      590 Mon Jun 17 22:38:01  root@hostyour.tv
(delivery temporarily suspended: connect to ziuri.me[104.31.3.1**]:25: Connection timed out)
                                         admin@ziuri.me

A36EF1E4F92F6      590 Sat Jun 15 13:14:01  root@hostyour.tv
(delivery temporarily suspended: connect to ziuri.me[2606:4700:31::681f:2bf]:25: Connection timed out)
                                         admin@ziuri.me

A32861E4F8C24     2602 Wed Jun 19 15:40:36  MAILER-DAEMON
(delivery temporarily suspended: connect to ziuri.me[104.31.2.1**]:25: Connection timed out)
                                         admin@ziuri.me

**Comment by yalh76** [comment]
where did this logs come from ?

**Comment by filmaidykai** [comment]
mailq

**Comment by yalh76** [comment]
Your server is trying to send mail to a server named ziuri.me to send him mails but it can reach it. Better to ask in the yunohost forum or in the yunohost chatroom

**Comment by filmaidykai** [comment]
aaa ok thanks

**Comment by JOduMonT** [comment]
> journalctl -u peertube -fe

would be easier with a grep like this
`journalctl -u peertube -fe|grep password -B1`
