### ISSUE TITLE
Error during upgrade

### ISSUE THREAD

**Issue by Thoma-HauC** [YunoHost-Apps/peertube_ynh#116]
Hello,

I am not able to upgrade peertube.
It seems something is wrong with youtube-dl module.
See the following file :
[peertube_issue_on_yunohost.txt](https://github.com/YunoHost-Apps/peertube_ynh/files/3378380/peertube_issue_on_yunohost.txt)

Thank you in advance for your help

Thoma

**Comment by yalh76** [comment]
nodejs is a bit unstable, can you retry to install peertube to check if you still have the same error

**Comment by Thoma-HauC** [comment]
Hello Yalh76,

I tried several times and the issue is reproducible.
Can I try something else?

Thoma

**Comment by yalh76** [comment]
Just tested, can you retry and give a link to the logs if it fails

**Comment by Thoma-HauC** [comment]
Hello Yalh76,

Here is the log file :
[20190713_bug_peertube.log](https://github.com/YunoHost-Apps/peertube_ynh/files/3389111/20190713_bug_peertube.log)

Thoma

**Comment by yalh76** [comment]
Ok then, I made another install on a new server. Install works fine. It seems related to you YunoHost.
Do you installed something related to youtube-dl ?

**Comment by Thoma-HauC** [comment]
This installation is running for more than 2 years.
But I do not think I have installed something related to youtube-dl on this machine.

On this machine, I have installed : Dokuwiki, Etherpad Mypads, Firefox Sync Server, Gogs, Jeedom, Jirafeau, Kanboard, Nextcloud, OpenSondage, Roundcube, Wallabag, Wordpress, riot and peertube.
There is also a MQTT server (mosquitto) and BLYNK server.

What can I check regarding youtube-dl?

Thanks for your support

**Comment by yalh76** [comment]
Is it an upgrade or an installation of peertube ?
Because you speak of an upgrade of peertube and the log you provided are about an installation...

If it's an upgrade, what is your current peertube_ynh version ?

**Comment by Thoma-HauC** [comment]
You are right, it is no longer an upgrade. I forgot to give you this information.
Something goes wrong during one of the attempts of upgrade and peertube disappeared.
Now I need to install it again.

**Comment by yalh76** [comment]
What kind of computer do you use ? 
A raspberrypi 1 ?
Have you seen https://github.com/Chocobozzz/PeerTube/issues/1273

**Comment by Thoma-HauC** [comment]
My hardware is a Cubietruck with around 400Gio of free disk space.

I start the same test as in the other thread but yarn was missing.
After installing yarn, test succeed in 32,52s.

I relaunch yunohost app install peertube but it exits with the same error.

Before this update, peertube was running like a charm. Is this a new dependency ?

**Comment by yalh76** [comment]
After more analysis, during mastodon install dependency, when node donwload and install youtube-dl module, it requires to download a binary https://ytdl-org.github.io/youtube-dl/index.html

Seems that another person has the same issue as you: https://github.com/przemyslawpluta/node-youtube-dl/issues/201

**Comment by Thoma-HauC** [comment]
Do you think a workaround is possible?
Or should I download something?

**Comment by yalh76** [comment]
I have no idea.. I more a Linux beginner..
Maybe you should ask at peertube repository https://github.com/Chocobozzz/PeerTube/

**Comment by Thoma-HauC** [comment]
Last question: Is there a tutorial about how to debug the installation script on YUNoHost?

**Comment by yalh76** [comment]
> 
> 
> Last question: Is there a tutorial about how to debug the installation script on YUNoHost?

I don't think but it's easy to read. But as far as I've seen and tested, your issue doesn't come from the install script
