### ISSUE TITLE
Unable to delete a previously subscribed instance

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#118]
Hello,

I want to delete all content from an another instance, so i unsubscribed and muted it from mine, but the instance's content is still there, mudding my instance's reputation without me being able to do anything about it. I have same problem for accounts from other instances. What must i do to unlock this embarassing situation ?

**Comment by yalh76** [comment]
please refer to https://github.com/Chocobozzz/PeerTube/
