### ISSUE TITLE
Can't login and token is invalid

### ISSUE THREAD

**Issue by GuillermoAnkh** [YunoHost-Apps/peertube_ynh#119]
Hello,
I install a new Peertube instance on my YunoHost (i have only one peertube instance). It's install on peertube.domaine.tld

When it finish without any error messages, i receive an email with my id and password root.
But when i go to my url of this instance i have a red message Token is invalid and i can't connect with root and mdp.
Do you have any idea to fix it ?

Bonjour,
J'installe une nouvelle instance Peertube sur mon YunoHost (je n'ai qu'une instance Peertube). C'est installer sur peertube.domaine.tld

Quand il se termine sans aucun message d'erreur, je reçois un email avec mon identifiant et mon mot de passe root.
Mais quand je vais à mon URL de cette instance, j'ai un message rouge Token n'est pas valide et je ne peux pas me connecter avec root et mdp.
Avez-vous une idée pour le réparer?

Thanks a lot / Merci beaucoup pour votre aide

Guillermo

**Comment by yalh76** [comment]
Hi @GuillermoAnkh 

Do you have a print screen ?

**Comment by GuillermoAnkh** [comment]
Hi @yalh76,

I could give you that https://nuage.ankh.gr/index.php/s/3q9c99QXybB5ynP

**Comment by yalh76** [comment]
Ok, I'm able to reproduce it. It seems to happen when you install peertube as a private instance.

Is it you case ?

**Comment by GuillermoAnkh** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Yes it's rightSo i must uninstall and re install it ?                                                                                                                                                                          De: notifications@github.comEnvoyé: 13 août 2019 22:05À: peertube_ynh@noreply.github.comRépondre à: reply@reply.github.comCc: guillaume.renaud@ankh.gr; mention@noreply.github.comObjet: Re: [YunoHost-Apps/peertube_ynh] Can't login and token is invalid (#119)  Ok, I'm able to reproduce it. It seems to happen when you install peertube as a private instance.
Is it you case ?

**Comment by yalh76** [comment]
> 
> #response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Yes it's rightSo i must uninstall and re install it ? 

Not for now, I will look at that, if I find a solution

**Comment by GuillermoAnkh** [comment]
More information : when i try to log in my instance it said : Invalid client: client is invalid 
I try it on private and public instance if it could help

**Comment by yalh76** [comment]
You also have that issue on a public instance ? because in the test we have made, the issue only happens on private instances.

**Comment by GuillermoAnkh** [comment]
I saw in your profile that your city is Paris, can we switch in French ?

Yes, i have test it on public and private instance. Same trouble and both instance.

**Comment by yalh76** [comment]
Yes we can.

Des tests que j’ai effectué sur peertube, l’erreur de token invalide n’apparait que lorsqu’on indique qu’une instance est privée lors de l’installation.
A priori ce n’est pas la seule app à rencontrer ce problème. A voir comment on peut résoudre le problème globalement.

**Comment by GuillermoAnkh** [comment]
J'ai fais les tests sur peertube1.domaine.tld (privé) et peertube2.domaine.tld (publique) et sur domaine.tld, mais les résultats sont les mêmes.
J'ai lu à certains endroits qu'il y avait parfois des problèmes de "temps" mais date me renvoi la bonne date et heure.

**Comment by alexAubin** [comment]
Following some investigation with @yalh76, the cause of the issue is described here : https://github.com/YunoHost/issues/issues/1420

From the app's side : 
- The issue apparently only appears if you install a 'private' instance (is_public set to False). Installing in public mode should fix the issue if that's okay for you
- There is a dirty and unsecure workaround that we discussed with @yalh76 about bypassing the SSOwat mechanism for some URI
- The real fix should happen in the core (implement a new setting in our SSO mechanism to not mess with Authorization header)
- The *real true ideal fix* would be that this app (and others) support Basic HTTP auth ... but I'm not really expert about this stuff and don't know if that's even possible or relevant ... but that sounds necessary if we ever want to have an SSO integration for these

**Comment by unklebonehead** [comment]
This issue just happened to me and it was installed as a public. But I had the signups shut off. I can still reach it through Thorium and watch my videos. But through Firefox Quantum 68.0.2 with cache and everything clear it wont let me log in or even see the local videos.
https://paste.yunohost.org/ikifihubah

**Comment by unklebonehead** [comment]
Does work in private tab

**Comment by unklebonehead** [comment]
To note, I had uninstalled Funkwhale and installed Grav plus my firefox on both my phone and Ubuntu had updated. But I have verified it is public and accessible from Thorium, in private tabs on my mobile and desktop browsers. Just not for any that I was signed in on before. Ive cleared all cookies and cache and history. Still only able to get on in private. Could this be a Firefox thing? Im going to reinstall Funkwhale this weekend and see if that might make it work. Lol. 
Ita worth a try.

**Comment by yalh76** [comment]
> To note, I had uninstalled Funkwhale and installed Grav plus my firefox on both my phone and Ubuntu had updated. But I have verified it is public and accessible from Thorium, in private tabs on my mobile and desktop browsers. Just not for any that I was signed in on before. Ive cleared all cookies and cache and history. Still only able to get on in private. Could this be a Firefox thing? Im going to reinstall Funkwhale this weekend and see if that might make it work. Lol.
> Ita worth a try.

From the tests we made it's not firefox dependant. We also had the issue with Chrome

**Comment by unklebonehead** [comment]
Looks like it was a Firefox issue for me. I updated them again and now I'm back to normal.

**Comment by unklebonehead** [comment]
It happened to me again. I noticed that I was still logged into my Yunohost in another tab. I logged out and no more invalid token.

**Comment by franckhomer** [comment]
Hi all,

I have the same issue but since today with the upgrade of Yunohost.
No problem to connect if i'm logged out of my yuno in other table. 
Same issu on Firefox or chrome for me.
