### ISSUE TITLE
Peertube v1.4.0

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#120]
Hey couple days ago peertube released version v1.4.0 so waiting for upgrade from you as well 

Cheers

**Comment by filmaidykai** [comment]
v1.4.1 aready here

Bug fixes
Fix too fast redundancy eviction
Fix broken auto blacklist page
Rename signup steps
Fix menu x overflow

**Comment by filmaidykai** [comment]
So wanna ask any news for new realise?

**Comment by yalh76** [comment]
;) feel free to do a PR for the upgrade to v1.4.1

**Comment by filmaidykai** [comment]
How?  :D I always doing that then is showing  up on yunohost panel upgrade section

**Comment by yalh76** [comment]
> 
> 
> How? :D I always doing that then is showing up on yunohost panel upgrade section

Start reading how to make a package https://yunohost.org/#/packaging_apps_start and then read https://yunohost.org/#/packaging_apps
