### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#121]
Hello,

My peertube instance became suddenly unusable for an unknown reason. According journalctl (https://stemy.me/zerobin/?e259f4916d131c82#9abYWKWgeyoJmd3hBzBJBBjt8qjnEfdMxFC+mzvgt7g=), the problem seems to be pgsql. I asked the question to the main peertube repository, but i think i need a solution specifically for the ynh app because they talk about a password i had to define, but the app never asked me to define any password.

**Comment by yalh76** [comment]
The peertube password is automatically defined during install. 
You can retrieve it in `/var/www/peertube/config/production.yaml` or doing `yunohost app setting peertube psqlpwd`

You will be able to change it in postgresl using pgadmin_ynh or with http://www.postgresqltutorial.com/postgresql-change-password/

**Comment by stemy2** [comment]
OK, but i didn't totally understood. It may be a dumb question, but the password indicated in production.yaml must match with what ?

**Comment by stemy2** [comment]
Nevermind, a reinstallation fixed everything.
