### ISSUE TITLE
Manually messing with nginx conf file should be avoided at all costs ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/peertube_ynh#123]
I'm sure there's a good reason for what happens here : 

https://github.com/YunoHost-Apps/peertube_ynh/blob/ef94fba50c6c0a860b0abd6f3367f4432ef9af6e/scripts/install#L165

but it's really not recommended to proceed that way ... The nginx configuration is going to be marked as manually modified, and will therefore not be updated to Yunohost's standard, and might even trigger bugs later like in https://forum.yunohost.org/t/nginx-ne-demarre-plus/9175 ... :confused:

**Comment by yalh76** [comment]
My bad... it's stemy2 effect, if something can goes wrong, it will.

I suppose that the good way to mess with nginx configuration is to use hooks?

**Comment by alexAubin** [comment]
Yea ... that's a bit more complicated than just a sed but that'd be the right way to proceed (though I dunno what's the exact motivation here ... naively I'd look if there isn't a way to somehow override this header in the app's nginx config ? But I guess you already tried that)

**Comment by yalh76** [comment]
ok then, I will look if I can override the header but as far as I remember, I wasn't able... 
It's 4 month old, so not sure: https://github.com/YunoHost-Apps/peertube_ynh/blame/ef94fba50c6c0a860b0abd6f3367f4432ef9af6e/scripts/install#L165
