### ISSUE TITLE
Unable to start peertube service

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#124]
Hello,

Whe i'm triyinng to start peertube, i have [these error messages](https://stemy.me/zerobin/?7f96eb35dd752a2c#uEaG6IukI+YkLTCLXNI+Qu2ySKvB9W7RDE7mPw/YFig=). I think the preblem is specific to the ynh app cause on the main project page, the dev said me to upgrade peertube -already up to date on my server- and nodejs to the version 10 -my server says the newest version is 8.16.1-.

**Comment by yalh76** [comment]
That's the problem, you updated nodejs.
Current peertube YunoHost package is 1.3.1 that require nodejs 8
So now, or you find a way to repair waht you broked or you wait for peertube_ynh to be updated to 1.4.1

**Comment by stemy2** [comment]
No, the problem was there before i updated nodejs to a newer version than the v.8. I updated it precisely because i though it would fix it.

**Comment by stemy2** [comment]
No, you didn't understand. I didn't updated nodjs before the error appeared. Then i updated it, thinking that it would solve the problem, but it didn't.
