### ISSUE TITLE
Upgrade to v2.0

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/peertube_ynh#129]
For tracability/visibility :)

Peertube v2.0 is out : https://github.com/Chocobozzz/PeerTube/releases/tag/v2.0.0

**Comment by gnouts** [comment]
What about ovh_fix branch ?

**Comment by yalh76** [comment]
ovh_fix branch planned ;)

**Comment by filmaidykai** [comment]
v2.1.0-RC1 did you will do something with this version or you will be waiting 2.2.0

**Comment by yalh76** [comment]
> 
> 
> v2.1.0-RC1 did you will do something with this version or you will be waiting 2.2.0

I prefer to wait for next stable release but feel free to do a PR if you think there are changes / improvements / bug fixes that is needed now without waiting 2.1.0
