### ISSUE TITLE
error when setting an application as default

### ISSUE THREAD

**Issue by IvanlokoBR** [YunoHost-Apps/peertube_ynh#136]
Hello, I'm testing yunohost on a Google cloud to confirm that it will work perfectly on my dedicated one, however when installing peertube when setting the error as the default (Can't make the app 'peertube' the default on the domain animecine.net is already used by the other app 'peertube')  
![image](https://user-images.githubusercontent.com/59476920/72950589-97c02080-3d6a-11ea-86cd-3f3a906840a3.png)

**Comment by yalh76** [comment]
Maybe because peertube is already the default on the domain you choose and because peertube requires dedicated domain

**Comment by IvanlokoBR** [comment]
@yalh76  I don't know if you can help me with another question is the conversion preset is very fast Do you know if it is possible to set it to very low to compress the videos more?

**Comment by yalh76** [comment]
> 
> 
> @yalh76 I don't know if you can help me with another question is the conversion preset is very fast Do you know if it is possible to set it to very low to compress the videos more?

I really don't know :/ I don't use peertube. Would be better to ask at peertube forum ^^
