### ISSUE TITLE
Unable to change the administrative setting by the admin

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/peertube_ynh#14]
It need to add /var/www/peertube/config/local-production.json with peertube owner:
```
touch /var/www/peertube/config/local-production.json
chown peertube:peertube /var/www/peertube/config/local-production.json
```

**Comment by anmol26s** [comment]
You mean /var/www/peertube/config/production.json is not owned by the peertube user?

**Comment by nemsia** [comment]
It does not exist on fresh install.

**Comment by anmol26s** [comment]
But why we need local-production.json? I did not understand. The configuration needs to be done in /var/www/peertube/production.yaml which is here https://github.com/YunoHost-Apps/peertube_ynh/blob/master/conf/production.yaml for YunoHost.

**Comment by nemsia** [comment]
Without is file all work well after the installation, but if you want to change anything in "administration > configuration" (Instance name, description, transcoding setting, ...) you have "Internal error" message and the log say : 
```
"error": "Error: EACCES: permission denied, open '/var/www/peertube/config/local-production.json'"
```

**Comment by anmol26s** [comment]
@nemsia Can you test the upgrade from testing for this issue?

**Comment by nemsia** [comment]
It work well, thank you ;)
