### ISSUE TITLE
Inaccurate instance metadatas

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#145]
Hello,

The section "Features found on this instance" does not correspond to the actual settings. Version is marked as unknown and enabled options are marked as disabled. The solutions i found are working only client-side ans are vanished if i reset the browser. Peertube developer just merged a fix in his own repository, could you update the YNH version so we could have it too ?

Thanks.

**Comment by yalh76** [comment]
The ynh version will be updated at next peertube release.
