### ISSUE TITLE
How to use peertube cli server tools

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/peertube_ynh#156]
I have some old files in my storage (and I guess in the database) which I want to delete/clean off. I guess [prune-storage](https://docs.joinpeertube.org/#/maintain-tools?id=prune-storagejs) is the right way to delete them.

peertube supports some [cli server tools](https://docs.joinpeertube.org/#/maintain-tools?id=server-tools.)
How to use these with yunohost?

**Comment by yalh76** [comment]
peertube cli is not included in the peetube release https://github.com/Chocobozzz/PeerTube/releases/download/v2.1.1/peertube-v2.1.1.tar.xz

**Comment by AkselRocks** [comment]
That confuses me!
The documentation is from version 2.1.1 and there are a bunch of scripts in /var/www/peertube/scripts/

**Comment by averyburnettmiller** [comment]
Sorry to bump an old thread, but I am also a bit confused! Are the CLI tool just not included in peertube_ynh?

**Comment by yalh76** [comment]
After re-reading https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#server-tools, CLI tools are included in peertube_ynh. Thanks for the comment.
