### ISSUE TITLE
Can't enable signup / open registration

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/peertube_ynh#158]
Hi,
I've installed peertube a year ago or so with signup disable.
Now, I want to turn it on. But the setting doesn't change anything.

Weird thing, I'm hosted on OVH and I used the ovh_fix branch. It works fine an another instance (not on OVH)

Weirder, all the other settings are applied correctly. For example I can enable/disable "HTTP import", I can view it's updated instantly on the about page summary. But signup stays disabled.

Weirderer, the signup setting is modify in /var/www/peertube/local-production.json.

I restart peertube.service each time and nginx too. Files permissions are set for peertube user. I have no errors in logs.

**Comment by yalh76** [comment]
Can you explain what changes you made to try to enable registrations ?

**Comment by gnouts** [comment]
I first try to enable it via the web interface (Administration>Configuration>Basic Configuration). I checked "signup enabled". Then "Update config". Green popup shows up.

I searched which files were modified in the config and I saw only /var/www/peertube/local-production.json is useful.
If I modify it manually, it's reflected in the web config.

Either way, the "signup" button never appeared.

(Are the others files really not useful ? - production.yaml, default.yaml)

**Comment by yalh76** [comment]
Welll i've tested from the master branch and the ovh_fix branch and enabling signup works.

By default configuration is in /var/www/peertube/config/production.yaml and changes made through the web interface is stored in /var/www/peertube/config/local-production.json as written in: https://github.com/Chocobozzz/PeerTube/blob/e61151b01c80e525db068ff12fcfe2c8ae04e1a4/config/production.yaml.example#L171-L181

Can you provide a yunopaste of :
- content of /var/www/peertube/config/
- content of /var/www/peertube/config/local-production.json

**Comment by gnouts** [comment]
Yep, I agree, it must be my setup issue. Problem is I can't afford to reinstall everything :/ 

Here are the logs :
* https://note.tigwali.fr/?ded188649166d3fc#IAot+CuNMEOlCqOiVZTjnXtO5aq4PhrQhlWrVfJFtX4=
* https://note.tigwali.fr/?902d16f4f7fbdb8a#JM0FRClru9jsa+BVOR3oxeUlc4N+tnd2Jfd0hMFGUo4=

**Comment by yalh76** [comment]
Well i tried your local-production.json on a freshly installed peertube and here is the result:
![image](https://user-images.githubusercontent.com/30271971/76910661-eabbdd00-68ae-11ea-8e76-6bca4af1e705.png)
Registrations opened...
And I was able to close is changing :
```
  "signup": {
    "enabled": false,
```
and restarting peertube service with `service peertube restart`

Have you tried to restart the service ? the server ?
Look at upstream peertube issues ?

**Comment by gnouts** [comment]
Ok then, this is obviously not an issue with the ynh package.
Thanks for your time, I'm closing this and I'll investigate on my side.
