### ISSUE TITLE
bittorrent-tracker@9.14.4: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by Kapu06** [YunoHost-Apps/peertube_ynh#163]
Hi, I followed the step to upgrade peertube on a OVH server.
And when I launch :
`cd /var/www/peertube && yarn install --production --pure-lockfile
`
I get : 
`yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error bittorrent-tracker@9.14.4: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`
I'm not used to yarn, so I tried `yarn add node` and the same message appears :/ How to solve it ?

**Comment by yalh76** [comment]
You should install nodejs 10 => look at the first step of the installation : https://github.com/YunoHost-Apps/peertube_ynh/tree/ovh_fix

**Comment by Kapu06** [comment]
Thanks I thought I had already done that the first time I installed it.
