### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/peertube_ynh#171]
**Describe the bug**
installation not working

**Versions**
- Hardware: odroid hc1 armhf v7
- YunoHost version: 3.8.4.8 stable
- I have access to my server: web interface
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: yes
  - If yes, please explain: posfix was configured to accept sending mail inside from outside in name of an account
- trying to install package version/branch: peetube stable

**To Reproduce**
install by web or cli same response, fail to install.

**Expected behavior**
install the peertube application correctly

**Logs**
https://paste.yunohost.org/raw/sexozebige
sorry for the link ;)

**Comment by yalh76** [comment]
Maybe it's because you are on armhf, but it's seems really like the error guys have on OVH VPS: https://github.com/YunoHost-Apps/peertube_ynh/issues/107

**Comment by franckhomer** [comment]
Hi, i have same issue with #107 
with the ligne 
$ cd /var/www/peertube && yarn install --production --pure-lockfile
To bypass the issue i made 2 step :
First -> $ cd /var/www/peertube
Then -> sudo yarn install --production --pure-lockfile
Since I do this i have no issue with upgrade.
I hope this can help you.

**Comment by rosbeef** [comment]
I try ovh_fix branch but not working, I didn't describe that i'm on debian stretch over buster lxc container.

**Comment by yalh76** [comment]
> 
> 
> I try ovh_fix branch but not working, I didn't describe that i'm on debian stretch over buster lxc container.

I don't know if there is some limitations on lxc...

**Comment by rosbeef** [comment]
working with the new version
