### ISSUE TITLE
how to setup an instance after installing peertube?

### ISSUE THREAD

**Issue by seanpeaceforever** [YunoHost-Apps/peertube_ynh#174]
Guys would u help plz?

just Installed peertube on my dedicated yunohot server, but how can I manage (setup-create instances - loading videos)..etc
I am interacting through command mode only, 
God bless all

**Comment by hieronymousch** [comment]
You should have got an email with credentials. Uses these to login on the peertube URL you installed it in. Instance is created with installation

**Comment by seanpeaceforever** [comment]
Thank u bro for your reply, you mean the e-mail of my  domain with yunohost or my web mail?   and  in yunohot I can not log in with GUI , do you know how to  activate GUI ,I am using command mode only, 
thank u

**Comment by yalh76** [comment]
Admin password has be sent to the email address given at the time of the installation.

**Comment by geopayme** [comment]
What if you never got an email?

**Comment by yalh76** [comment]
you can retrieve the password using `yunohost app setting peertube admin_pass`
