### ISSUE TITLE
PeerTube Admin access

### ISSUE THREAD

**Issue by geopayme** [YunoHost-Apps/peertube_ynh#189]
I've installed PeerTube on my server via YunoHost, all went all with the acceptation, I have no details now to login the admin section of PeerTube. The instructions I have are vague any ideas?

**Comment by geopayme** [comment]
Email was never send at time of installation so who can I recover or resend the root mail

**Comment by yalh76** [comment]
from ssh you can retrieve it with : `yunohost app setting peertube admin_pass`
