### ISSUE TITLE
PeerTube App Storage 

### ISSUE THREAD

**Issue by geopayme** [YunoHost-Apps/peertube_ynh#190]
I have been trying to define a new volume in Digital Ocean as an alternative option but I have not had much luck, even thought my volume is mounted, yunohost does see it and PeerTube does not use it! 

![DigitalOcean Droplet Console 2020-11-18 21-27-13](https://user-images.githubusercontent.com/8299759/99578073-e8cd8f00-29e4-11eb-8e25-17a677f41349.png)

**Comment by geopayme** [comment]
a look at my fstab 


![DigitalOcean Droplet Console 2020-11-18 21-30-05(1)](https://user-images.githubusercontent.com/8299759/99578284-4bbf2600-29e5-11eb-9dbc-7d58ea259a54.png)

**Comment by geopayme** [comment]
Here is my settings.yml

![DigitalOcean Droplet Console 2020-11-18 21-33-18(1)](https://user-images.githubusercontent.com/8299759/99578656-cc7e2200-29e5-11eb-8404-f962feadb1fc.png)

**Comment by geopayme** [comment]
I manage to connect the volume drive and show it on the Yunohost [System Resources] and updated the DataDir path to the path of the volume `datadir storage /media/storage` but the peertube platform still uploads in the old root drive.

![DigitalOcean Droplet Console 2020-11-18 22-58-32](https://user-images.githubusercontent.com/8299759/99590543-25ee4d00-29f6-11eb-8233-3dfc531e4bbe.png)

**Comment by yalh76** [comment]
> 
> 
> I manage to connect the volume drive and show it on the Yunohost [System Resources] and updated the DataDir path to the path of the volume `datadir: /media/storage` but the peertube platform still uploads in the old root drive. Any ideas how to get PeerTube to see the new storage?


Where and how did you change the path of the volume `datadir: /media/storage`
