### ISSUE TITLE
Upgrade testing branch to 3.0.0-rc.1

### ISSUE THREAD

**Issue by groblochon** [YunoHost-Apps/peertube_ynh#191]
New version is pre-released here : https://github.com/Chocobozzz/PeerTube/releases/tag/v3.0.0-rc.1

May upgrade testing branch like https://github.com/groblochon/peertube_ynh, it's working for me with live stream feature (install only).

We need to open 1935 port :

    $ yunohost firewall allow TCP 1935

**Comment by yalh76** [comment]
I prefer to wait to next stable version.

**Comment by arthurlogilab** [comment]
Yeah stable version is out! https://github.com/Chocobozzz/PeerTube/releases/tag/v3.0.0 (cf https://framablog.org/2021/01/06/peertube-v3-ca-part-en-live ). Exciting. Happy to help test out the upgrade.

**Comment by mathieunicolas** [comment]
Hi, how can I install the v3 in my yunohost distrib ? Shall I wait for the official YNH package update, or can I try to tweak the current install ?
Thanks 😊

**Comment by yalh76** [comment]
V3.0.0 is in testing branch => https://github.com/YunoHost-Apps/peertube_ynh/pull/194, you can install it using `yunohost app install https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`

**Comment by mathieunicolas** [comment]
> V3.0.0 is in testing branch => #194, you can install it using `yunohost app install https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`

ok, thanks, so if my instance is already installed it's not possible to upgrade it directly or thanks to your command, is it ?

**Comment by arthurlogilab** [comment]
@yalh76 thanks for this upcoming new release ! 

@mathieunicolas you can upgrade using `sudo yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh/tree/testing --debug`

**Comment by yalh76** [comment]
> @yalh76 thanks for this upcoming new release ! 
> 
> 
> 
> @mathieunicolas you can upgrade using `sudo yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh/tree/testing --debug` 

There is a 3.0.1
And I forgot to open the new port in actual testing....

**Comment by discapacidad5** [comment]
> Prefiero esperar a la próxima versión estable.

I am anxiously awaiting the release of version 3 every day it entered checked to see if it is already available

**Comment by arthurlogilab** [comment]
Upgrade an internal instance of peertube with the testing branch and live feature seems to work ! (quick test with OBS). :clap:
