### ISSUE TITLE
FFMPEG Error during 3.0.1 update causes transcoding to fail

### ISSUE THREAD

**Issue by hexydes** [YunoHost-Apps/peertube_ynh#199]
During the update from 2.4.0 to 3.0.1 something happened with FFMPEG (and regrettably, I didn't catch the error in a screenshot). Other than that, everything seemed to work fine, until I tried changing my transcoding from Webtorrent to HLS. Now, I'm noticing all my videos fail during transcoding with an FFMPEG error.

Have you guys seen any errors around FFMPEG during updates for this version, and is there a way I can manually fix this (update the FFMPEG version or something?) This is for a Debian 9 installation environment.

**Comment by arthurlutz** [comment]
Hi @hexydes, any chance of migrating up to debian buster (10)  to solve your problem ? 

Can you show the output of `apt policy ffmpeg`  ?

**Comment by hexydes** [comment]
I'm hesitant to do the Debian 10 update, because if there's an issue, I'm not sure if I'd be able to troubleshoot it (and Yunohost gives warnings about potential issues...)

I'll try grabbing the output of that in a bit, thanks!

**Comment by hexydes** [comment]
Here's the output of `apt policy ffmpeg`:

`ffmpeg:
  Installed: 7:3.2.15-0+deb9u2
  Candidate: 7:3.2.15-0+deb9u2
  Version table:
 *** 7:3.2.15-0+deb9u2 500
        500 http://security.debian.org stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     7:3.2.14-1~deb9u1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages`

**Comment by yalh76** [comment]
Actual version of peertube_ynh require Buster ...
