### ISSUE TITLE
Problem while upgrading peertube

### ISSUE THREAD

**Issue by mathieunicolas** [YunoHost-Apps/peertube_ynh#201]
**Describe the bug**
I got an error when I try to upgrade peertube from 3.0.0 to 3.0.1

**Versions**
- Hardware: OVH dedicated server / Debian Buster
- YunoHost version: 4.1.7.1
- I have access to my server: SSH & WebAdmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: yes
  - If yes, please explain: I installed a Discourse server I plugged into YNH through some basics NGINX tweaks, long time ago, and it never caused any problem since then
  - The running peertube instance has been installed from the testing branch few weeks ago, and I got the error when I try to upgrade with the webadmin or with the CLI
  - the logs say "warning Port 1935 is needs to be available for this app" but this port is already open

**To Reproduce**
Launch the update with the webadmin or the CLI ( I tried this command, to tell YHN the upgrade has to be done from the master branch, but it keeps giving me the same error : `sudo yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh/tree/master` )

**Expected behavior**
The update should run smoothly ?

**Logs**
https://paste.yunohost.org/raw/tebefadovi

Thanks for the help ! It's actually not a huge update but I'd like to be able to do it !

**Comment by mathieunicolas** [comment]
Okay, I should have dig few more minutes on this problem...
After trying different things, I finally stopped the peertube service, and the upgrade worked just fine. Do you guys think it's a normal behaviour, or is my YNH distro kind of broken somewhere ?

**Comment by JPPalus** [comment]
I've got the same problem :

https://paste.yunohost.org/raw/xebomejusu

But stopping the peertube service didn't work for me though.

**Comment by yalh76** [comment]
> 
> 
> I've got the same problem :
> 
> https://paste.yunohost.org/raw/xebomejusu
> 
> But stopping the peertube service didn't work for me though.

As written in your log, Port 1935 is not available on your yunohost server

**Comment by JPPalus** [comment]
> As written in your log, Port 1935 is not available on your yunohost server

And yet it is. This "Port 1935 is needs to be available for this app" is present both in my log and in the OP one.

**Comment by stemy2** [comment]
Same problem

https://paste.yunohost.org/raw/vapazofupu

Now, my peertube app is not accessible anymore, i just have the nginx default page.
