### ISSUE TITLE
Upgrade the App to v3.1.0

### ISSUE THREAD

**Issue by LoXan007** [YunoHost-Apps/peertube_ynh#210]
Hi,

for the case that you don't know it currently: Chocobozzz has released the Peertube version v3.1.0 (https://github.com/Chocobozzz/PeerTube/releases)
So i would be very happy if you could update the App soon.

Thanks very much in advance.

**Comment by yalh76** [comment]
There is an ongoing PR for that => https://github.com/YunoHost-Apps/peertube_ynh/pull/209
