### ISSUE TITLE
Install don't complete on Debian 10 Azure Microsoft

### ISSUE THREAD

**Issue by MiisterChipsSs** [YunoHost-Apps/peertube_ynh#214]
Hello,

I recently wanted to install PeerTube with YunoHost on Linux (debian 10.9).
The virtual machine is on Microsoft Azure.

This is my logs : https://paste.yunohost.org/raw/xihayilero

I don't know what to add more.

thanks for the help

**Comment by yalh76** [comment]
it seems that there is not root user in your YunoHost... did you delete it ?
