### ISSUE TITLE
Server is unable to play local videos

### ISSUE THREAD

**Issue by zanhesl** [YunoHost-Apps/peertube_ynh#217]
For some reason, videos on my peertube yunohost instance are not loading. 
Videos from followed instances work as fine.

![](https://framacolibri.org/uploads/default/original/2X/b/b2628114901e485f64e3286a35de363c8ca10c06.png)

![](https://framacolibri.org/uploads/default/original/2X/b/b837ba13eb47232c67f7d25943af0a99df2e459a.png)

Diagnosis show no problems with server/dns etc.

<img width="1226" alt="Снимок экрана 2021-04-08 в 12 39 55" src="https://user-images.githubusercontent.com/48605213/114004636-87a93980-9867-11eb-96f4-ebc4b17aa28b.png">

<img width="1188" alt="Снимок экрана 2021-04-08 в 12 39 41" src="https://user-images.githubusercontent.com/48605213/114004603-7fe99500-9867-11eb-9c4c-2cfcb120d18a.png">

**Comment by yalh76** [comment]
You should look at peertube logs when you try to see a video:

Peertube logs can be seen from a ssh command line:
`journalctl -feu peertube`

**Comment by zanhesl** [comment]
Thank you for your suggestion. it turned out, that I've used symlink on my remote machine incorrectly. So it had nothing to do with yunohost. Closing the issue.
