### ISSUE TITLE
Videos/Upload Cors Issue 

### ISSUE THREAD

**Issue by zanhesl** [YunoHost-Apps/peertube_ynh#221]
Hello Everyone, suddenly request videos/upload from my local server stopped working because of some CORS issues. However, I am able to upload video from my peertube instance directly. Code worked perfectly a week ago. Do you have any ideas why my code has stopped working?

Errors:
![image](https://user-images.githubusercontent.com/48605213/115154657-b94eab80-a084-11eb-8a12-c119a6020f7b.png)

![image](https://user-images.githubusercontent.com/48605213/115154671-c23f7d00-a084-11eb-8d8a-1ddba41a9f94.png)

My code:

![image](https://user-images.githubusercontent.com/48605213/115154679-cb304e80-a084-11eb-9f04-da3f4de5abeb.png)

It worked properly before the latest update. I'm currently using 3.1.0 version.

**Comment by zanhesl** [comment]
<img width="924" alt="Снимок экрана 2021-04-19 в 11 06 35" src="https://user-images.githubusercontent.com/48605213/115202683-51897680-a0ff-11eb-8a48-d1307578be2f.png">

Adding this to nginx.conf is doing nothing at all

**Comment by zanhesl** [comment]
After further debugging I've found out that server indeed does not return Access-Control headers

My query:

`curl -H "Origin: https://pocketnet.app"   -H "Access-Control-Request-Method: POST"   -H "Access-Control-Request-Headers: X-Requested-With"   -X OPTIONS --verbose   https://pocketnetpeertube3.nohost.me/api/v1/videos/upload`

result:

<img width="727" alt="Снимок экрана 2021-04-19 в 13 22 55" src="https://user-images.githubusercontent.com/48605213/115221458-5dcaff00-a112-11eb-9610-b50d21d08721.png">

So how can I update server config?

**Comment by zanhesl** [comment]
It turned out that new Nginx config does not handle preflight requests on `/videos/upload`, so REST API is unusable. I could make a PR to solve this (essentially just add OPTIONS handler for /videos/upload route).

**Comment by yalh76** [comment]
yes, I let you do a PR ;)

**Comment by fflorent** [comment]
@zanhesl  If you change the server config, could you also propose a PR for the upstream nginx config file?

https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube

**Comment by yalh76** [comment]
last peertube nginx is already
