### ISSUE TITLE
Upgrading to peertube ynh3 version completely broke my Peertube

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/peertube_ynh#223]
### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: *VPS bought online
- YunoHost version: 4.1.8 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no
- 
### Steps to reproduce
I updated Peertube to the ynh3 version via the admin panel. The update shows no errors at first but looking at the logs there are some https://paste.yunohost.org/raw/oqihixisax. 
But now the entire instance is not accessible - https://videos.trom.tf/ I see no error just a blank page....

The bad thing is that if I restore to the previous version no videos work. I can navigate it but there are no thumbnails and no local videos work.

### Logs

https://paste.yunohost.org/raw/oqihixisax

**Comment by TROMsite** [comment]
I have restored a backup from yesterday. No videos or thumbnail work. :(

**Comment by AkselRocks** [comment]
Same here.

The Website is completly blank.

No errors in the logfile.

**Comment by TROMsite** [comment]
The website is accessible for me and my friends, using different VPNs from different countries. Even here it shows up https://sitechecker.pro/website-down/ with a screenshot and all. Can you please try in a private browser window?

**Comment by TROMsite** [comment]
I am also wondering why I get this warning "Unknown user:" when I restore Peertube.

**Comment by AkselRocks** [comment]
Check on https://sitechecker.pro/website-down/: website is "UP", but no screenshot.

Check in private browser Window: Still just a blank page.

**Comment by TROMsite** [comment]
One more thing: other videos work, such as https://videos.trom.tf/videos/watch/6f9371cf-9f6a-4932-9add-9a5e42a5ef9f that are from other instances. Everything seems to work for the backup restoration, except videos.

**Comment by TROMsite** [comment]
> Check on https://sitechecker.pro/website-down/: website is "UP", but no screenshot.
> 
> Check in private browser Window: Still just a blank page.

This is very bizarre. Can you tell me from what country you are trying to access it? I can give it a shot to try a VPN from there

**Comment by AkselRocks** [comment]
To make it clear: I have the same issue with my instance and tested MY website -> website is "UP", but no screenshot.

From my VPN in Austria your website is up and shows screenshot.

**Comment by TROMsite** [comment]
Oh ok so you are having the same issue after upgrading? Because is true, after I upgraded I get the same a blank page and nothing. But even the restore doesn't make the website functional.

**Comment by yalh76** [comment]
What are the URL of your peertube ?
Currently doing a test upgrade from version 3.0.1~ynh1

**Comment by TROMsite** [comment]
This is mine https://videos.trom.tf - downgraded to ynh2 and is broken as described above. If I upgrade to ynh3 I get a blank page like @AkselRocks

**Comment by yalh76** [comment]
ok and @AkselRocks yours?

@TROMsite stop trying restore / upgrade, first have to figure what is the blank page issue

**Comment by AkselRocks** [comment]
My peertube url is: https://daschauher.aksel.rocks

**Comment by yalh76** [comment]
> 
> 
> My peertube url is: https://daschauher.aksel.rocks

Perfect: there are issue to load .js files ...

![image](https://user-images.githubusercontent.com/30271971/115872080-aa2f7b00-a441-11eb-9edc-a29e46775d03.png)



ynh3 is about directory permissions..
I will check why .js don't load

**Comment by yalh76** [comment]
@AkselRocks, can you try to do from the command line :

```
chown -R $app:www-data "/var/www/peertube"
```

 to see if it's enough to solve your problem

**Comment by AkselRocks** [comment]
@yalh76 
sudo chown -R peertube:www-data "/var/www/peertube" -> fixed blank page, but no thumbnails and no video play.

**Comment by yalh76** [comment]
fine, we are moving forward ....
I will test to upload a file on my own test.

@TROMsite : you can upgrade and apply same fix for the blank page

**Comment by tomdereub** [comment]
Maybe it's better two issues ? this one about upgrade problem, and a new one about the restore problem ? Now it's hard to know if we're talking about a working instance of peertube that's just upgraded and get a blank page, or about an instance upgraded, removed, restored but not working, upgraded again, etc...

**Comment by TROMsite** [comment]
I already upgraded like @yalh76  said. It is working now to access it, but the custom settings (CSS) are gone + no thumbnails and local videos do not work. https://videos.trom.tf/

**Comment by yalh76** [comment]
@AkselRocks, to fix thumbnails and video, can you execute:
```
chown -R peertube:www-data "/home/yunohost.app/peertube/storage"
```

**Comment by yalh76** [comment]
Seems OK for @AkselRocks, Can you do the same @TROMsite  ?

**Comment by tomdereub** [comment]
Ok, my case : I upgraded, blank page, removed, restored backup, and it was working but without thumbnails and local video.
Now I've done 

```
chown -R peertube:www-data /var/www/peertube
chown -R peertube:www-data /home/yunohost.app/peertube/storage
```

And it's all working again, thanks. I'll wait the fix before trying to upgrade again.

**Comment by AkselRocks** [comment]
@yalh76 chown -R peertube:www-data "/home/yunohost.app/peertube/storage" -> Thumbnails and playing video work again! 

Configuration (Sitename, description, etc) seem to be set to default.

**Comment by yalh76** [comment]
> 
> Configuration (Sitename, description, etc) seem to be set to default? I think I changed (at least) the site name displayed on top ...

Yes config file is reset during upgrade but previous config file is backuped. All should be written in the logs of the upgrade

**Comment by TROMsite** [comment]
`chown -R peertube:www-data "/home/yunohost.app/peertube/storage"`

Works. Thanks! How to restore the configs now?

**Comment by TROMsite** [comment]
Ok just restore the file that was backed-up. Thanks! All seem to work now. Awesome!

**Comment by TROMsite** [comment]
So is it safe to upgrade to ynh4 now?

**Comment by yalh76** [comment]
> 
> 
> So is it safe to upgrade to ynh4 now?

yes this will do the same command line you have done :)

**Comment by TROMsite** [comment]
Done! All works well. By the way I am curious why the production.json file got overwritten? Shouldn't that be ignored?

**Comment by yalh76** [comment]
It's now ignored ... I've done that too quick, not thinking of consequences ^^

**Comment by AkselRocks** [comment]
After upgrade #244 the same issue ("completely broke peertube") appears.

As above
```
chown -R peertube:www-data /var/www/peertube
chown -R peertube:www-data /home/yunohost.app/peertube/storage
```
solves the issue.
