### ISSUE TITLE
3.0.1 >> 3.1.0 Upgrade Issues

### ISSUE THREAD

**Issue by TILvids** [YunoHost-Apps/peertube_ynh#225]
### Describe the bug

While upgrading from 3.0.1 to 3.1.0, upgrade appears to be successful, but when loading the site post-update, all configurations are lost, CSS styling is missing, etc. Seems similar to this issue (https://github.com/YunoHost-Apps/peertube_ynh/issues/223#issuecomment-826012129) but in following the permissions changes outlined there, it did not resolve the issue.

Also, tried updating any of the settings in the config, none of them will take. Possibly a permissions problem with local-production.json?

I can provide logs, if necessary. Site is tilvids.com

**Comment by TILvids** [comment]
Ok, as an update, I grabbed a backup copy of my local-production.json file and pushed it to the server. I had to reconfigure some permissions/ownership on it, but I think it got things mostly back to working order. I still was having trouble changing anything on the admin page, but it must be working with whatever config was set up before. It really looks like something in the 3.1.0 ynh update really broke something with the upgrade process, as it relates to server configs.

**Comment by TILvids** [comment]
Further update, while I at least have things back so that they look correct on the front-end, I cannot make any changes in the web admin page (just says server error any time I try to commit a change). So there's clearly a permissions error going on somewhere. Any advice?

**Comment by yalh76** [comment]
I've done a PR to not update local-production.json during upgrade process

For the issue you still have, can you look at peertube logs when you try to make changes in the web admin ?

**Comment by yalh76** [comment]
I will wok on https://github.com/YunoHost-Apps/peertube_ynh/issues/226

**Comment by TILvids** [comment]
> I've done a PR to not update local-production.json during upgrade process
> 
> For the issue you still have, can you look at peertube logs when you try to make changes in the web admin ?

When I go to make a change on the web admin, I get:

"Server Error. Please retry later."

As the popup in the corner. In the logs, the most recent thing I see after doing that is:

```
error[4/24/2021,` 1:37:22 PM] Error in controller.

{
  "err": "Error: EACCES: permission denied, open '/var/www/peertube/config/local-production.json'"
}

error[4/24/2021, 1:37:28 PM] Error in controller.

{
  "err": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:124:11)\n    at Object.join (path.js:1039:7)\n    at self.getCaptionStaticPath (/var/www/peertube/dist/server/models/video/video-caption.js:113:23)\n    at self.getFileUrl (/var/www/peertube/dist/server/models/video/video-caption.js:122:53)\n    at Object.videoModelToActivityPubObject (/var/www/peertube/dist/server/models/video/video-format-utils.js:270:26)\n    at self.toActivityPubObject (/var/www/peertube/dist/server/models/video/video.js:1013:37)\n    at /var/www/peertube/dist/server/controllers/activitypub/outbox.js:42:43\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)"
}
```

So definitely looks like a permissions thing. I've tried changing the permissions a few times on that file, but no luck. Any ideas?

**Comment by TILvids** [comment]
Will continue this in https://github.com/YunoHost-Apps/peertube_ynh/issues/226 so as not to have different conversations going.
