### ISSUE TITLE
After upgrade: New settings can not saved + not able to import video from youtube

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/peertube_ynh#226]
### Describe the bug
After upgrade to version ynh4 I can not 
- change configurations (Site name, desc, etc) -> error, try again later
- import video via download (for example: from youtube)

Next to save button (trying to save configuration): "There are errors in the form: Please enter an administrator email address. "

### Context

- Hardware: *VPS bought online 
- YunoHost version: 4.1.8 (stable).
- I have access to my server: *Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 

### Steps to reproduce
If 
- trying to import video, there is no folder for that (just "upload file" and "go live" folder)

If:
- set Admin email in Administration/Configuration/base settings/ 
- use save button
- Error, Service error, try again later

If:
- change sitename in  Administration/Configuration/Instance Information, 
- save button is grey
- "there are errors ..." next to save button

### Expected behavior

able to import from yt

able to save the settings

**Comment by TILvids** [comment]
I think I'm having similar issues (see: https://github.com/YunoHost-Apps/peertube_ynh/issues/225). I think there's some permissions issue with the latest update. It also looks like the local-production.json file is not getting properly brought over during the update. I manually uploaded a backup, which restored most of my settings, but I still can't make any changes under the admin page, and the custom theme won't load still.

**Comment by yalh76** [comment]
will look at that

**Comment by TILvids** [comment]
> I've done a PR to not update local-production.json during upgrade process
> 
> For the issue you still have, can you look at peertube logs when you try to make changes in the web admin ?

When I go to make a change on the web admin, I get:

"Server Error. Please retry later."

As the popup in the corner. In the logs, the most recent thing I see after doing that is:

```
error[4/24/2021,` 1:37:22 PM] Error in controller.

{
  "err": "Error: EACCES: permission denied, open '/var/www/peertube/config/local-production.json'"
}

error[4/24/2021, 1:37:28 PM] Error in controller.

{
  "err": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:124:11)\n    at Object.join (path.js:1039:7)\n    at self.getCaptionStaticPath (/var/www/peertube/dist/server/models/video/video-caption.js:113:23)\n    at self.getFileUrl (/var/www/peertube/dist/server/models/video/video-caption.js:122:53)\n    at Object.videoModelToActivityPubObject (/var/www/peertube/dist/server/models/video/video-format-utils.js:270:26)\n    at self.toActivityPubObject (/var/www/peertube/dist/server/models/video/video.js:1013:37)\n    at /var/www/peertube/dist/server/controllers/activitypub/outbox.js:42:43\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)"
}
```

So definitely looks like a permissions thing. I've tried changing the permissions a few times on that file, but no luck. Any ideas?

**Comment by AkselRocks** [comment]
@TILvids If you change the permission like this, the settings can be saved:
`sudo chmod 640 /var/www/peertube/config/local-production.json`

@yalh76 
After changing the rights like written above, the admin email can be saved and then sitename and the other settings can be changed/saved.
I need to set all configs (import videos, etc) again. not good.

**Comment by AkselRocks** [comment]
@yalh76 

/var/www/peertube/config/local-production.json
/var/www/peertube/config/production.yaml

have the rights "peertube:peertube". shouldn't they have peertube:www-data after the changes in #223 ?

**Comment by yalh76** [comment]
> 
> 
> @yalh76
> 
> /var/www/peertube/config/local-production.json
> /var/www/peertube/config/production.yaml
> 
> have the rights "peertube:peertube". shouldn't they have peertube:www-data after the changes in #223 ?

Nop with peertube:www-data : nginx is allowed to read the file including secrets and database password....

**Comment by yalh76** [comment]
3.1.0~ynh5 put the good rights on local-production.json => `chmod 600`

**Comment by TILvids** [comment]
Ok, so just to confirm, the following should be true:

Both of the following should be chown to peertube:peertube (**_not_** peertube:www-data)
```
/var/www/peertube/config/local-production.json
/var/www/peertube/config/production.yaml
```
The following should be chmod to 600

`/var/www/peertube/config/local-production.json`

All true?

**Comment by yalh76** [comment]
Yes exactly, as far as I understand Linux rights
