### ISSUE TITLE
error in journalct

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/peertube_ynh#229]
Hi,

While I'm trying to figure it out why the peertube service is noticed as failed at shutdown, I've noticed something in journalctl
Don't know if it is important to you or ot but I thought I might notify you about it.
```
Apr 29 20:07:37  peertube[1665]: (node:2316) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
Apr 29 20:07:37  peertube[1665]: (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by yalh76** [comment]
It's more something to report on the upstream application => https://github.com/Chocobozzz/PeerTube/

**Comment by boistordu** [comment]
okey thanks will do
