### ISSUE TITLE
Slight server modification

### ISSUE THREAD

**Issue by zanhesl** [YunoHost-Apps/peertube_ynh#236]
Hello, I want to slightly modify existing peertube server (running with yunohost), so I've made a few changes on my local dev setup in typescript files and then compiled server files to dist directory. It runs perfectly on my local macheine. 

However, when I am trying to substitute folder on my instance server (that is located in `/var/www/peertube/dist`) and then restarting the server, it fails to start (see attached screenshot). All I get is 502 server error
<img width="911" alt="Снимок экрана 2021-05-18 в 14 02 11" src="https://user-images.githubusercontent.com/48605213/118640442-a5ac7700-b7e1-11eb-8303-f2fb6e1ad4a3.png">

Contents of dist folder:
<img width="371" alt="Снимок экрана 2021-05-18 в 14 05 04" src="https://user-images.githubusercontent.com/48605213/118640770-0d62c200-b7e2-11eb-9bb4-c58f51a7df6a.png">

What is a correct way of doing this? Or how can I get more detailed logs of this process?

Thanks.

**Comment by yalh76** [comment]
Did you chown the files to peertube:peertube ?

Putting files in /var/www/peertube, files will be deleted during next upgrade :/
