### ISSUE TITLE
Installation fails: permission denied to /var/www/.yarnrc

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/peertube_ynh#237]
From an IRC support request:

https://paste.yunohost.org/raw/isejayutop

**Comment by tituspijean** [comment]
Issue is still occurring. 😢 

https://paste.yunohost.org/raw/miduzoxawi

**Comment by yalh76** [comment]
Maybe you should delete `/var/www/.yarnrc` because peertube_ynh nether works in `/var/www/` but only in `/var/www/$app`
