### ISSUE TITLE
Support for Debian Stretch

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/peertube_ynh#24]
The app is failing on Debian Stretch as stated here https://github.com/YunoHost-Apps/peertube_ynh/issues/20#issuecomment-392446830. I am not sure about the real issue is upgrading to Stretch or something particularly related to the YunoHost instance of the user. As of now I am assuming its a Stretch issue.
Someone already using the YunoHost 3 beta can test and give the feedback please.

Important logs:
https://paste.yunohost.org/tukuvomezo
https://paste.yunohost.org/bafowacayi
https://paste.yunohost.org/uvunotujox.diff

**Comment by anmol26s** [comment]
@mokas01 The app is multi-instance. So can you try to install the app on the other domain and see if there is same error while installation too? It would be good if you provide the installation logs too.

**Comment by anmol26s** [comment]
Ok, so I found that the connection to the database is failing. 
`Attention : pg_dump: [archiver (db)] connection to database "peertube_peertube" failed: FATAL:  la base de données « peertube_peertube » n'existe pas`

**Comment by mokas01** [comment]
I have no important video on my instance. Multi-instance installation failed "peertube is already installed" — at the early beginning of the install. I try to remove and re-install. Should solve (or at least clarify) the issues

**Comment by anmol26s** [comment]
Can you try to install postrgesql-9.4 again `sudo apt-get install postgresql-9.4 postgresql-client-9.4` ?
And show `ps -ef | grep postgre`.

**Comment by mokas01** [comment]
ok. It appears it is a psql issue. I'll try again once I've solved that migration issue…
https://paste.yunohost.org/inohemakix.sql

as for psql 9.4 : all packages are already installed

> ps -ef | grep postgre
> root      2523 31916  0 11:05 pts/0    00:00:00 grep postgre

**Comment by anmol26s** [comment]
You should remove the postrgesql  `sudo apt-get --purge remove postgresql\*` and then try again the installation of the app.

**Comment by mokas01** [comment]
Even this install failed, but for some other reason (l.174 and following)
https://paste.yunohost.org/jifiweqare.sql

**Comment by anmol26s** [comment]
Can you manually install and see which dependency is failing?
`sudo apt-get install postgresql ffmpeg redis-server redis-tools mailutils`

**Comment by anmol26s** [comment]
Do 
`apt-get install sysstat`
Then install the app again.

**Comment by mokas01** [comment]
it was already installed, set as manual install…
here are the logs of the (still failing) install :/ 

https://paste.yunohost.org/siracodoqa.sql

Once again, thanks for your help and support !

**Comment by anmol26s** [comment]
There is conflict between postrgesql-9.4. Which branch are you using? I hope the latest testing branch.
`yunohost app install --verbose https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`
If you are using this. Remove the postrgesql-9.4 and then try again.

**Comment by mokas01** [comment]
installing using the testing failed.
No postgresql-9.4 installed anymore

https://paste.yunohost.org/egafugoluw.sql

**Comment by anmol26s** [comment]
What? sleep still need more time? What is the hardware of the system being installed.
We are almost there. Try one more time to install the testing branch otherwise, I will increase the sleep time little more.

> I tried several times, and it sometimes froze on the yarn line :
> 
> yarn install --production --pure-lockfile --silent --cache-folder /var/cache/yarn/

Yes, its normal while the dependency are being installed.

**Comment by mokas01** [comment]
it worked (although I had an uncatched error in the send an email at the end part). Checking the installation to confirm everything is ok, and cleaning the log from all passwords and i send it to you if you want

**Comment by mokas01** [comment]
Here are the logs : https://paste.yunohost.org/ibavikefep.diff
I replaced the given pass by ***pass***
The reason it is slow and 30 secs are needed is perhaps it is a small ARM board (olimex lime2)
once again a huge thank you for taking the time to help and improve :heart:

**Comment by anmol26s** [comment]
Thanks 
For helping to improve the app. I will merge the sleep time increase to 30 sec so that ARM devices don' get an error.

If you want to test further you can try to backup the app, then remove and then restore. As restore is failing and need testing. It would be good to see ARM result.
1. `yunohost backup create  --ignore-system --aap peertube -n peertube_backup --verbose `
2. `yunohost app remove --verbose peertube`
3. `yunohost backup restore --verbose peertube_backup`

**Comment by anmol26s** [comment]
Mail issue is related to yunohost. See https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/34 and I think there is a fix here https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/35/commits/35ef8e1cad11533f2cd1201534514084de519151.
I will try it with peertube in upcoming merge.

**Comment by anmol26s** [comment]
I am closing this issue as this should be resolved now. You can reopen if you face the issue again.
