### ISSUE TITLE
No plugins work anymore after updating to 	3.2.1

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/peertube_ynh#242]
### Describe the bug

After the last ynh peertube upgrade, no plugins work anymore. Installing gives an error "Bad Request". The already installed plugins also do not work. Maybe it is an issue with folder permission? IDK.

### Context

- Hardware: *VPS bought online
- YunoHost version: 4.2.6 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

**Comment by TROMsite** [comment]
I think it is a permission issue since I also cannot read the log files for peertube.

**Comment by oufmilo** [comment]
#216 It's the same issue

**Comment by TROMsite** [comment]
I upgraded to 3.2.1~ynh3 that should have fixed the issue. But it did not. At least for me. Same issue as stated above. So you know ;)
