### ISSUE TITLE
Empty page after upgrade

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/peertube_ynh#247]
### Describe the bug

After upgrading to version 3.2.1~ynh2, I get a empty page. There are 403 errors in the network panel (which seems related to the latest commits) :

![image](https://user-images.githubusercontent.com/371705/122540495-fc97ad00-d028-11eb-809f-2e5c084e8fa6.png)

### Context

- Hardware: Old laptop or computer
- YunoHost version: 3.2.1~ynh2
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: N/A
- If upgrading, current package version: 

### Steps to reproduce

1. Run the upgrade to version 3.2.1~ynh2
2. Try to upgrade from version `3.2.1~ynh1` to `3.2.1~ynh2`

### Expected behavior

The PeerTube home page should be displayed.

**Comment by oufmilo** [comment]
chown -R peertube:www-data /home/yunohost.app/peertube/storage
 chown -R peertube:www-data /var/www/peertube

Should fix the problem

**Comment by fflorent** [comment]
I restored the backup before the upgrade, it works also well.

Thanks for your answer and for your work :pray:

**Comment by AkselRocks** [comment]
see #223
