### ISSUE TITLE
Peertube removed after failed upgrade

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#258]
### Describe the bug

I tried to upgrade peertube, but instead, yunohost uninstalled it and now, the subdomain redirect to the default nginx page. And if i install peertub it says it's already installed.

### Context

- Hardware: desktop pc
- YunoHost version: 4.2.6.1
- I have access to my server: full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: script in background that prevent the regular wiping of the dnsmasq conf file
- Using, or trying to install package version/branch:
- If upgrading, current package version: 3.2.1

### Steps to reproduce

- 
    ```sh
    sudo yunohost app upgrade
    ```

### Expected behavior

App upgrade.

### Logs

https://paste.yunohost.org/raw/upeqoboloh
https://paste.yunohost.org/raw/begugipune
https://paste.yunohost.org/raw/tezarevile

**Comment by yalh76** [comment]
Upgrade fails because it wasn't able to download `node-v14.17.4` 
You should check if you have enough space.
And if it's ok; first remove peertube and try to restore it: a backup was made during upgrade : `peertube-pre-upgrade1`
