### ISSUE TITLE
Button update configuration is inactive.

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/peertube_ynh#26]
Hello
I just installed Peertube version 1.0.0-beta.7
When I go into administration, I can not make any changes because the button update configuration is inactive.

**Comment by lesamarien** [comment]
Solution found: you had to fill the field "Your Twitter username"

**Comment by isAAAc** [comment]
and howto do if you don't have any twitter account ?

**Comment by anmol26s** [comment]
I think this is the Peertube core bug rather then YunoHost packaging bug. It was working prior to this release.

**Comment by anmol26s** [comment]
There is a similar issue on Peertube already. https://github.com/Chocobozzz/PeerTube/issues/379

**Comment by lesamarien** [comment]
I do not know whether to have a valid twitter account for this to work. I do not think so because Peertube is not connected to Twitter

**Comment by anmol26s** [comment]
I have opened an issue https://github.com/Chocobozzz/PeerTube/issues/625
