### ISSUE TITLE
Red PopUp "token is invalid"

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#27]
Hi, 
i don't already looked the logs, but i have a red popup on the right bottom corner, telling that "the token is invalid"
am i alone to have this ?
How can i patch this ?

**Comment by anmol26s** [comment]
Do you see it on all videos? Does the videos play despite of the error? I think this is not related to app packaging.
You should create an issue on the Peertube core app page. The log file is located at  /home/yunohost.app/peertube/storage/logs/peertube.log. And find the way to debug it.
Remember Peertube is still in beta :baby: .

**Comment by isAAAc** [comment]
yep, i'll  do that in few hours/days if it's still alive, 
can i keep this issue open during this time, or do you prefer closing it ?

**Comment by quentinDupont** [comment]
Same issue here !

**Comment by anmol26s** [comment]
@quentinDupont 
I did not understand your comment. Why are you not able to create user? Are you not able to login from your root account?

**Comment by quentinDupont** [comment]
Yes I was login as root but it had an error.
But actually, I found the solution :smile: 

I update manually the file /etc/ssowat/conf.json.persistent with :
  
```
{
    "redirected_urls": {
    },
    "skipped_url": [
	"mydomain.fr/.well-known/acme-challenge"
    ],
    "unprotected_urls": [
	"mydomain.fr/.well-known/acme-challenge"
    ]
}

```
and restart nginx 

`sudo service nginx restart`

and it works !

**Comment by anmol26s** [comment]
Nice, I will investigate on that.
Thanks

**Comment by madmaxlamenace** [comment]
I have the same problem yesterday and i have the same problem.
Yesterday problem was resolved just restarting nginx.
But today i already have the same message.

**Comment by anmol26s** [comment]
@madmaxlamenace 
I think its related to core app. Can you watch the videos ? Is it happening to the video hosted on your server only or the videos from other instances too?

**Comment by madmaxlamenace** [comment]
I can't watch the videos. and For now i don't add other instances. my problem is on local videos i don't know if the problem is on other instances. Like yesterday an nginx restart solved the problem.
Is it related to YunoNoHost and the sso ?

**Comment by anmol26s** [comment]
Try other videos. I had this issue from a Youtube imported video. But others are working normally.

Try your local video in this format and see if its work:
https://peertube.cpy.re/static/webseed/f78a97f8-a142-4ce1-a5bd-154bf9386504-360.mp4

And if its  not working there is something else. And you will have to look logs /home/yunohost.app/storage/log/peertube.log.

**Comment by quentinDupont** [comment]
Actually I also had the same issue the day after.. I will look at your advices @anmol26s

**Comment by madmaxlamenace** [comment]
If you have Token problem open another session with the browser. Maybe the SSO and Peertube authentification can't be used together.

**Comment by quentinDupont** [comment]
Oh sh*t you're right ! If i'm not connected to my Yunohost, I don't have any problem while going to Peertube

**Comment by anmol26s** [comment]
I am not able to reproduce this.
Do we need to login from SSO and PeerTube account at the same time? 
Have you tried to delete the PeerTube channel and created a new channel and then tried to watch video?
Have to tried disabling "Automatically play video"?

**Comment by anmol26s** [comment]
Temp fix:
https://forum.yunohost.org/t/yunohost-peertube-et-yunohost-probleme-de-jetons-didentification/4571/3

**Comment by anmol26s** [comment]
Can you show me logs please?

**Comment by isAAAc** [comment]
sure :)
i just tried a new reinstall : 
https://paste.yunohost.org/raw/lulepihemu 

` 2018-10-14 15:46:56,551: WARNING - W: The repository 'https://dl.yarnpkg.com/debian stable Release' does not have a Release file.
2018-10-14 15:46:56,552: DEBUG - + local exit_code=100
2018-10-14 15:46:56,552: WARNING - E: Impossible de rÃ©cupÃ©rer https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
2018-10-14 15:46:56,552: DEBUG - + '[' 100 -eq 0 ']'
2018-10-14 15:46:56,553: WARNING - E: Le tÃ©lÃ©chargement de quelques fichiers d'index a Ã©chouÃ©, ils ont Ã©tÃ© ignorÃ©s, ou les anciens ont Ã©tÃ© utilisÃ©s Ã  la place.
2018-10-14 15:46:56,553: DEBUG - + trap '' EXIT `

**Comment by tomdereub** [comment]
Same problem here, peertube is working well, but if i'm connected with a yunohost account in the same browser, I have a "token is invalid" error.
About yarnpkg problem, maybe you can find a solution here : https://forum.yunohost.org/t/mastodon-admins-update-the-gpg-key-for-yarnpkg/3898

**Comment by isAAAc** [comment]
> About yarnpkg problem, maybe you can find a solution here : https://forum.yunohost.org/t/mastodon-admins-update-the-gpg-key-for-yarnpkg/3898

nope i still have the same error after  `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

**Comment by yalh76** [comment]
this issue is now solved with the last update of peertube_ynh, you can update doing:
`yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`
