### ISSUE TITLE
Root login failed after fresh install

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#28]
Hi, 
i just done (twice) a fresh resintall of peertube_ynh
using the command as root : 
`yunohost app install https://github.com/YunoHost-Apps/peertube_ynh`

but i can't login as root user using the new password sended by mail.

- the first time , i tried the solution used in https://github.com/YunoHost-Apps/peertube_ynh/issues/13 : 
`cd /var/www/peertube && NODE_ENV=production npm run reset-password -- -u root`
but i had the same trouble, new password didn't works
so i tried `npm rebuild` without more succes, then, `npm install`  and restarted peertube service, result was a 502 error even a nginx restart... so i reinstalled from scratch the peertube_ynh

- second time, same trouble, i refresh the page with ctrl+F5, but the password sended by mail is still not working.

Waiting for order to continue investigation ;)

**Comment by anmol26s** [comment]
```
$ sudo service nginx restart
$ sudo systemctl stop peertube
$ sudo systemctl start peertube
$ sudo journalctl -feu peertube
```

**Comment by isAAAc** [comment]
you're the boss, 
root login OK after those steps :/ 
Issue can be closed if you don't need more information ;)
