### ISSUE TITLE
Migration script for upgrade to v4.0

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#287]
Hello,

I just saw in the last peertube changelog that after upgrade, we have to execute manually a migration script (mentioned below) to migrate HLS files name. Will you integrate it in the upgrade process for the YNH upgrade ?

`cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-4.0.js`

**Comment by BDouze** [comment]
I have added it to the pull request I just created for updating peertube to 4.0.0 : https://github.com/YunoHost-Apps/peertube_ynh/pull/289/commits/c288ec16aa9c1919a15994564d16a38c1e189f3e

But I'm not sure how this should be handled for future upgrades.
I guess it should not be run when upgrading to 4.1.0 if upgrading from 4.0.0 but it should still be run if upgrading from an older version (upgrading from 3.4.1 directly to 4.1.0 for example)

**Comment by yalh76** [comment]
merged into master
