### ISSUE TITLE
App stuck at level 6 due to reference to Jessie

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/peertube_ynh#294]
### Describe the bug

As per the title, the linter performs a basic grep for `jessie` in the script files and states we should clean it up.

Culprit is https://github.com/YunoHost-Apps/peertube_ynh/blob/0f77bb6e7441698b762bde38698c510dc0a4438e/scripts/upgrade#L100

Should we take a leap and remove it? Jessie was a loooong time ago. 😅

**Comment by yalh76** [comment]
Fixed by #290
