### ISSUE TITLE
Unable to log in as root/admin after installation

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/peertube_ynh#30]
After installing a new instance of PeerTube, I was unable to log in as the root / administrator account. Tracking the installation, I found at least three different sets of user and password generated by the installer.

- One set is generated on installation, and the password is sent to the chosen account by email. In theory it should be able to be reset via NPM, but the installer apparently doesn't configure the Node.js environment correctly, so the command fails.
- Another set appears on /var/www/peertube/config/production.yaml, next to the username "peertube". 
- A final set appears on a pair of lines from the log file /home/yunohost.app/peertube/storage/logs/peertube.log, next to the username "root".

Attempting all the permutations of these (with usernames "root", "admin", "peertube" and the email corresponding to my administrator account) on the user login field of the web UI has had no result. Attempting to request a password reset to said email does send the link to reset, but the resulting password doesn't work either. Creating a new account by adjusting the production configuration file, and then entering with said account, does work, however the account has no administration permissions and therefore can't follow any users outside of its instance.

**Comment by anmol26s** [comment]
Sorry for the inconvenience you faced. Please run the following commands and login with the username **root** and password you received on your email.

```
$ sudo service nginx restart
$ sudo systemctl stop peertube
$ sudo systemctl start peertube
$ sudo journalctl -feu peertube
```
You can do **ctrl+c** to stop the logs.

**Comment by csolisr** [comment]
Nothing much on the systemctl logs apparently. Whenever I attempt to log in, the following message appears:

Jun 19 20:08:13 azkware.net peertube[20638]: [peertube.azkware.net:443] 2018-06-19 20:08:13.311 info: 200.30.189.98 - csolisr [20/Jun/2018:00:08:13 +0000] "POST /api/v1/users/token HTTP/1.0" 401 58 "https://peertube.azkware.net/login" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"

And not much else unfortunately, not an error message or anything.

**Comment by csolisr** [comment]
After noticing the "duplicate" tag, I noticed that the fix that the other user applied also applies on my instance! Perhaps it would be useful to add the patch if it's not risky for security.

**Comment by anmol26s** [comment]
Temp fix:
https://forum.yunohost.org/t/yunohost-peertube-et-yunohost-probleme-de-jetons-didentification/4571/3

**Comment by isAAAc** [comment]
hi @anmol26s , i have the same issue : can't login with the id sent by mail during the install ; do you want i open a new issue ?

**Comment by JanSeW** [comment]
I had the same mistake with me. It took the simple restart of nginx and Peertube with the commands mentioned above to get access.

**Comment by yalh76** [comment]
This issue is now solved, you can install peertube_ynh doing:
`yunohost app install https://github.com/YunoHost-Apps/peertube_ynh`
