### ISSUE TITLE
Multi user administration of a channel, possible ?

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/peertube_ynh#310]
Hello,
I like a lot Peertube but I'm "falling of my chair" after discovering it seems not possible to share administration of a channel between users.
Am I wrong ? Any plugin or modification possible ?
It's a basic fonction for any collaborative work, I'm very disapointed.
Any help or suggestion is welcome.
Sincerely.
Yan

**Comment by yalh76** [comment]
hello,
You should ask at peertube repository: https://github.com/Chocobozzz/PeerTube/
It's not YunoHost specific
