### ISSUE TITLE
Fail to update from peertube 4.10 to 4.11

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/peertube_ynh#320]
### Describe the bug

update from peertube 4.10 to 4.11 fail

### Context

- Hardware: *odroid xu4 (armv7)/debian buster/lxd-lxc*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: lxc
  - ldap config in peertube 

- Using, or trying to UPDATE package version/branch: 4.1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

-[x] *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade peertube
    ```
-[x] *If you used the webadmin, please perform the equivalent command from the CLI first.* 

### Logs

https://paste.yunohost.org/raw/wavupadizi

**Comment by fflorent** [comment]
You just seem to have had connection issues:

> 
> 2022-03-24 17:49:33,016: DEBUG - $ test -n "$NOCLIENT" || (cd client && yarn install --pure-lockfile)
> 2022-03-24 17:49:34,666: DEBUG - yarn install v1.22.18
> 2022-03-24 17:49:35,254: DEBUG - [1/4] Resolving packages...
> 2022-03-24 17:49:37,714: DEBUG - [2/4] Fetching packages...
> 2022-03-24 17:50:34,432: DEBUG - info **There appears to be trouble with your network connection. Retrying...**
> 2022-03-24 17:51:07,365: DEBUG - info There appears to be trouble with your network connection. Retrying...
> 2022-03-24 17:51:40,692: DEBUG - info There appears to be trouble with your network connection. Retrying...
> 2022-03-24 17:52:13,855: DEBUG - info There appears to be trouble with your network connection. Retrying...
> 2022-03-24 17:52:49,049: DEBUG - error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-7.5.3.tgz: **ESOCKETTIMEDOUT**".
> 2022-03-24 17:52:49,053: DEBUG - info If you think this is a bug, please open a bug report with the information provided in "/var/www/peertube/client/yarn-error.log".
> 2022-03-24 17:52:49,055: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 2022-03-24 17:53:12,409: DEBUG - error Command failed with exit code 1.
> 2022-03-24 17:53:12,412: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 2022-03-24 17:53:13,425: DEBUG - + ynh_exit_properly
> 

Ensure to have an internet connection (`ping registry.yarnpkg.com`) and simply try again your command. If it works, please keep us informed.

**Comment by rosbeef** [comment]
> ping registry.yarnpkg.com
> PING registry.yarnpkg.com(2606:4700::6810:1823 (2606:4700::6810:1823)) 56 data bytes
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=1 ttl=55 time=3.82 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=2 ttl=55 time=3.86 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=3 ttl=55 time=4.29 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=4 ttl=55 time=4.18 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=5 ttl=55 time=4.70 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=6 ttl=55 time=3.68 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=7 ttl=55 time=4.34 ms
> 64 bytes from 2606:4700::6810:1823 (2606:4700::6810:1823): icmp_seq=8 ttl=55 time=3.62 ms
> 

i will check because other app give me the same error but i can ping
