### ISSUE TITLE
After upgrading to 4.1.0 from 4.0.0, performance is heavily degraded

### ISSUE THREAD

**Issue by TILvids** [YunoHost-Apps/peertube_ynh#321]
After upgrading to 4.1.0 from 4.0.0, performance is heavily degraded. The only solution I've been able to find so far is to do a hard-reboot of the server, which appears to bring performance back to normal for a few hours, before it eventually is degraded again. This is exhibited by extraordinarily long load-times for pages to load, which is immediately resolved after rebooting (for a time). It is also making it hard to post links to videos on social media as thumbnails don't get properly pulled (likely due to degraded performance).

**Comment by fflorent** [comment]
Try to upgrade to version 4.1.1 which fixes performance issues.

https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v411

Keep us if this works or not.

**Comment by TILvids** [comment]
Ok, will try that update tonight and report back. Thanks.

**Comment by TILvids** [comment]
Well, not great. The upgrade failed.

https://paste.yunohost.org/raw/lecorivudu

**Comment by TILvids** [comment]
Paging @yalh76 since he seems to generally know what happened when things break. :)

**Comment by TILvids** [comment]
Digging through the output of 'journalctl -eu peertube' makes me think it is similar to this PeerTube issue https://github.com/Chocobozzz/PeerTube/issues/1204

I'm getting a bunch of warnings about "message": "could not create unique index \"actor_url\"" and duplicate keys, which makes me wonder if something is timing out before the service can start back up during installation?

**Comment by TILvids** [comment]
I'm going to close this issue and start a new one, since this is no longer about performance.
