### ISSUE TITLE
 let the user enable gpu acceleration through an option

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/peertube_ynh#324]
PeerTube suggests to bring some additions in the systemd service that are not present in ours.

https://docs.joinpeertube.org/maintain-configuration?id=systemd-unit-with-reduced-privileges

~~This commit also seems to me to be a bad move, as~~ we seem to prefer an enhancement for some users (gpu hardware acceleration) instead of security which concerns every users: https://github.com/YunoHost-Apps/peertube_ynh/commit/f0448d53fe03b17ef65b1f12c54287ec3329ea9e

~~I suggest to revert and suggest later an option to let the user enable the gpu hardware acceleration.~~

EDIT: the documentation says `Some directives can be changed to improve security!`. My bad, my original message was tough. I don't suggest to revert the commit anymore but instead suggest a PR to let the user enable gpu acceleration through an option (I can work on this).

**Comment by lapineige** [comment]
I don't understand what setting affects GPU hardware acceleration.
