### ISSUE TITLE
Playback not possible for embedded videos because X-Frame is disabled in nginx

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/peertube_ynh#34]
The embeded playback doesn't work on mastodon, you click on play and nothing append.
Example: https://mstdn.nemsia.org/@nemsia/100328154283919921

It work on other peertube instance:
https://mstdn.nemsia.org/@nemsia/100328256117794882

**Comment by anmol26s** [comment]
Can you try to update with this branch and see if it gets fixed?

`$ yunohost app upgrade -u https://github.com/YunoHost-Apps/peertube_ynh/tree/iframe_fix peertube`

**Comment by nemsia** [comment]
Thank you, with this branch and cache cleaning all work well. 👍

**Comment by anmol26s** [comment]
But I will not close this issue. Its not perfect solution.

**Comment by rigelk** [comment]
hello - the issue has been raised recently (in french) on https://framacolibri.org/t/video-bloque-par-la-politique-x-frame-options/8148
