### ISSUE TITLE
import from other peertube instance does not work

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/peertube_ynh#340]
Describe the current behavior

import fom YT does work but
import from other peertube instance does NOT work
Steps to reproduce

. Click publish > import with URL
Paste URL from a peertube video
Says : "Congratulations, the video behind https://xxx.xx.xx/w/eQSYgM9gEWETcJEEhLuZhb will be imported! You can already add information about this video."
most of the fields are filled :-)
When you click "upate" button at the end of the page, it says "Sorry, but something went wrong
Video not found
Describe the expected behavior

No response
Additional information

VPS
PeerTube Version | 4.2.2
Yunohost 11.0.9.14

under /my-library/video-imports

I see this error:

```
ffprobe exited with code 1
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e3e2bdea00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e3e2bdea00] moov atom not found
/home/yunohost.app/peertube/storage/tmp/d47afe5d772c6402d69e01d24af8ddba6b73c788c326f2b6479283b1f4626782-import.mp4: Invalid data found when processing input
```

some logs: https://paste.yunohost.org/raw/efamimosup

Did asked already here: https://github.com/Chocobozzz/PeerTube/issues/5244

What could I try - Thanks for help

**Comment by rocky-III** [comment]
someone in the PT forum said to use 'yt-dlp'  instead of 'youtube-dl' 
How to install yt-dlp under YNH?

**Comment by rocky-III** [comment]
@yalh76    How to install yt-dlp under YNH?

**Comment by rocky-III** [comment]
> PeerTube installs and manages youtube-dl/yt-dlp binaries by itself

https://github.com/Chocobozzz/PeerTube/issues/5244#issuecomment-1243625857 @Chocobozzz 

 than the described problem must have a different cause. - 

What could i try ??? THANKS

**Comment by rocky-III** [comment]
>  admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                                                   
>     sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found    
> 
> It means yunohost isn't following the standard peertube installation.
> 
> On a standard installation it would output something similar:
> 
> root@workstation:~# /var/www/peertube/storage/bin/./yt-dlp -v
> [debug] Command-line config: ['-v']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
> [debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-17-amd64-x86_64-with-glibc2.31 (glibc 2.31)
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg git-2022-09-10-c92edd9 (setts), ffprobe git-2022-09-10-c92edd9
> [debug] Optional libraries: certifi-2020.06.20, sqlite3-2.6.0
> [debug] Proxy map: {}
> [debug] Loaded 1670 extractors

https://github.com/Chocobozzz/PeerTube/issues/5244#issuecomment-1244103703

**Comment by rocky-III** [comment]
@yalh76 pleas reopen this issue

**Comment by rocky-III** [comment]
still get this
```
admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                  
sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found      
```

**Comment by yalh76** [comment]
Storage is not in `/var/www/peertube` but at `/home/yunohost.app/peertube/storage/`

**Comment by yalh76** [comment]
Wasn't it a feature from peertube 4.3.0 ?

**Comment by fflorent** [comment]
> Wasn't it a feature from peertube 4.3.0 ?

I don't think so. I am the author of https://github.com/Chocobozzz/PeerTube/pull/5135 and this is not meant to fix issue about importing videos from other PeerTube instances.
