### ISSUE TITLE
Bind9 install problem

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#35]
Hey Im using SYS dedicated server with Debian 9.4 Stretch (stable) (64bits) so from start install by this command bash <(wget -q -O- https://install.yunohost.org/) I got fail 
[FAIL] Bind9 is installed and might conflict with dnsmasq. Uninstall it first, or if you know what you are doing, run this script with -f.
[INFO] Installation logs are available in /var/log/yunohost-installation_20180715_120932.log

any Idea what I have to do

**Comment by anmol26s** [comment]
`$ sudo apt-get autoremove apache2.2 bind9`

**Comment by filmaidykai** [comment]
But after that they dont install rouundcube

**Comment by anmol26s** [comment]
I did not understand why the roundcube would not get install without bind9.

bash <(wget -q -O- https://install.yunohost.org/) is for installing YunoHost on Debian stretch 9. And Peertube and Roundcube are app which get installed over YunoHost.

If you are getting trouble in getting YunoHost installed, then you should write on the forum. https://forum.yunohost.org
