### ISSUE TITLE
Trouble getting root password

### ISSUE THREAD

**Issue by JohnnyPicnic** [YunoHost-Apps/peertube_ynh#351]
I don't have e-mail setup and am having trouble getting the root password.
I've tried `yunohost app setting peertube admin_pass` but get no response.

```
Last login: Sun Nov  6 14:27:40 2022 from 192.168.1.119
darren@stream:~$ yunohost app setting peertube admin_pass
Error: yunohost command must be run as root or with sudo.
darren@stream:~$ su -
Password: 
root@stream:~# yunohost app setting peertube admin_pass
root@stream:~# 
```

**Comment by fflorent** [comment]
It's because it is not stored in the yunohost settings.

Run the following commands:
```bash
sudo su # so you log in as root
su - peertube # so you log in as peertube
cd /var/www/peertube # adapt if you have multiple instances of peertube
export PATH="/opt/node_n/n/versions/node/16/bin:$PATH"
echo "YOUR_PASSWORD_HERE" | NODE_CONFIG_DIR="/var/www/peertube/config" NODE_ENV=production npm run reset-password -- -u root
```

You can use a temporary password and then change it on the web UI

**Comment by JohnnyPicnic** [comment]
Thanks for the quick replay! Where do I find or what is the password for user peertube?

**Comment by fflorent** [comment]
Actually you cannot, you have to reset it by the procedure I gave you above

**Comment by JohnnyPicnic** [comment]
Account is not available?
```
admin@stream:~$ sudo su
root@stream:/home/admin# su - peertube
This account is currently not available.
root@stream:/home/admin# ~
```

**Comment by fflorent** [comment]
Oops, I missed the `-s /bin/bash`:
```bash
su - peertube -s /bin/bash # so you log in as peertube
```

I updated the procedure above

**Comment by JohnnyPicnic** [comment]
Cheers that worked. Thank you very much!

**Comment by fflorent** [comment]
You're welcome!
Could you please close the issue then at it resolved?
