### ISSUE TITLE
Question: change domain

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/peertube_ynh#364]
### Describe the bug

Question: How to change domain?

### Context

- Hardware: VPS bought online 
- YunoHost version: 11.0.11
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

Change domain in Admin panel.

**Comment by yalh76** [comment]
Cause of federation / activitypub, change_url has not been implemented, but if someone want to implement it and support that feature, he can submit a PR ;)

**Comment by AkselRocks** [comment]
I would do it, if I were able to do it. :-/
