### ISSUE TITLE
multi-instance: Yes or No?

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/peertube_ynh#367]
### multi-instance: Yes or No?

Description says: "This app is multi-instance (you can have more then one PeerTube instance running on a YunoHost server)" 
but when trying to install a second instance it says: "It is already installed and can't be installed more than once. "

### Context

- Hardware: VPS bought online 
- YunoHost version: 11.1.5.5
- I have access to my server: Through SSH 
- Using, or trying to install package version/branch: peertube_ynh 5.0.1~ynh1

### Steps to reproduce

- when having installed a peertube_ynh installed try to install another one

### Expected behavior

Able to install another instance on the same server.

**Comment by yalh76** [comment]
nope, peertube_ynh is not multiinstance.

https://github.com/YunoHost-Apps/peertube_ynh/blob/d46fef72bcc2014ba7e817dd4f41e5d065971f5f/manifest.json#L25
