### ISSUE TITLE
Not working to import from youtube

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/peertube_ynh#369]
I reported it here https://github.com/Chocobozzz/PeerTube/issues/5621 - it seems that we have to update yt-dlphttps://github.com/yt-dlp/yt-dlp#update but the command doesn't work` -bash: yt-dlp: command not found`

Anyone knows of a fix?

**Comment by fflorent** [comment]
The binary is located at `/home/yunohost.app/peertube/storage/bin/yt-dlp`

Can you attempt an upgrade using the below command?
```bash
python3 /home/yunohost.app/peertube/storage/bin/yt-dlp -U
```

**Comment by tio-trom** [comment]
Worked but it seems it is up to date...


```
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by fflorent** [comment]
Alright, can you attempt a new import? It should normally work.

If not, can you share the output of `journalctl -f -u peertube` while you attempt to import the video?

**Comment by tio-trom** [comment]
Ok maybe it got updated more recently. Now it works....

Thanks!
