### ISSUE TITLE
[Temp fix provided] Peertube can't send mail

### ISSUE THREAD

**Issue by maitorouge** [YunoHost-Apps/peertube_ynh#37]
I juste install Ynh 3.0.0.1
Install the package
Everything looks fine
I can see the peertube main page
But my server never send me an email for my administrator password, so i check the log with

>  sudo journalctl -feu peertube

The first lines of the logs show me this : 

 `juil. 25 01:29:44 peern.pw systemd[1]: Started PeerTube daemon.
juil. 25 01:29:47 peern.pw peertube[3184]: > peertube@1.0.0-beta.9 start /var/www/peertube
juil. 25 01:29:47 peern.pw peertube[3184]: > node dist/server
juil. 25 01:30:05 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:05.106 info: Database peertube_peertube is ready.
juil. 25 01:30:09 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:09.477 info: Creating application account.
juil. 25 01:30:09 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:09.649 info: Generating a RSA key...
juil. 25 01:30:10 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:10.433 info: Creating a default OAuth Client.
juil. 25 01:30:10 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:10.468 info: Client id: pxwzqzw5bmy5tc73e4584whtjljuhx5v
juil. 25 01:30:10 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:10.472 info: Client secret: fgrOdonYgGlCasbg3ExPeZhDiCHB6a9A
juil. 25 01:30:10 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:10.494 info: Creating the administrator.
juil. 25 01:30:10 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:10.807 info: Generating a RSA key...
juil. 25 01:30:11 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:11.516 info: Generating a RSA key...
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.232 info: Username: root
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.233 info: User password: wocafezedefutapo
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.242 info: Using localhost:25 as SMTP server.
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.251 info: Testing SMTP server...
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.289 info: Connection established to 127.0.0.1:25 {
juil. 25 01:30:12 peern.pw peertube[3184]:   "meta": {
juil. 25 01:30:12 peern.pw peertube[3184]:     "component": "smtp-connection",
juil. 25 01:30:12 peern.pw peertube[3184]:     "sid": "BYyXfdCKaI",
juil. 25 01:30:12 peern.pw peertube[3184]:     "tnx": "network",
juil. 25 01:30:12 peern.pw peertube[3184]:     "localAddress": "127.0.0.1",
juil. 25 01:30:12 peern.pw peertube[3184]:     "localPort": 56822,
juil. 25 01:30:12 peern.pw peertube[3184]:     "remoteAddress": "127.0.0.1",
juil. 25 01:30:12 peern.pw peertube[3184]:     "remotePort": 25
juil. 25 01:30:12 peern.pw peertube[3184]:   }
juil. 25 01:30:12 peern.pw peertube[3184]: }
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.588 info: Successfully connected to SMTP server.
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.656 info: Server listening on localhost:9000
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.657 info: Web server: https://peern.pw
juil. 25 01:30:12 peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 01:30:12.668 info: Connection closed {
juil. 25 01:30:12 peern.pw peertube[3184]:   "component": "smtp-connection",
juil. 25 01:30:12 peern.pw peertube[3184]:   "sid": "BYyXfdCKaI",
juil. 25 01:30:12 peern.pw peertube[3184]:   "tnx": "network"
juil. 25 01:30:12 peern.pw peertube[3184]: }
`
So I tried the login "root" and the password "wocafezedefutapo" this doesn't work

I tried also to reset the password with the form on the login interface of course the mail never arrived and the log show me this : 

`juil. 25 02:16:24 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:24.839 info: 92.102.104.115 - - [25/Jul/2018:02:16:24 +0000] "GET / HTTP/1.0" 304 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.163 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/config/ HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.166 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/videos/categories HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.171 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/videos/languages HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.191 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.270 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/videos/licences HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.274 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/videos/privacies HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:25 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:25.417 info: 92.102.104.115 - - [25/Jul/2018:02:16:25 +0000] "GET /api/v1/videos/?start=0&count=28&sort=-views HTTP/1.0" 304 - "https://peern.pw/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.142 info: 92.102.104.115 - - [25/Jul/2018:02:16:36 +0000] "POST /api/v1/users//ask-reset-password HTTP/1.0" 204 - "https://peern.pw/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.148 info: Processing email in job 2.
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.156 info: Connection established to 127.0.0.1:25 {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "meta": {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "component": "smtp-connection",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "sid": "f1DXr5ygaaE",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "tnx": "network",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "localAddress": "127.0.0.1",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "localPort": 58092,
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "remoteAddress": "127.0.0.1",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "remotePort": 25
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.268 info: Sending message <02d0bd6e-ad45-cf66-4e56-bd79670326cb@peern.pw> to <gr.gualerzi@gmail.com> {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "meta": {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "component": "smtp-transport",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "tnx": "send",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "messageId": "<02d0bd6e-ad45-cf66-4e56-bd79670326cb@peern.pw>"
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.313 error: Send error for <02d0bd6e-ad45-cf66-4e56-bd79670326cb@peern.pw>: Can't send mail - all recipients were rejected: 553 5.7.1 <admin@peern.pw>: Sender address rejected: not logged in {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "meta": {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "component": "smtp-transport",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "err": "Error: Can't send mail - all recipients were rejected: 553 5.7.1 <admin@peern.pw>: Sender address rejected: not logged in\n    at SMTPConnection._formatError (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)\n    at SMTPConnection._actionRCPT (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1425:28)\n    at SMTPConnection._responseActions.push.str (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1378:30)\n    at SMTPConnection._processResponse (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)\n    at SMTPConnection._onData (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)\n    at Socket._socket.on.chunk (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "tnx": "send"
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.314 error: Send Error: Can't send mail - all recipients were rejected: 553 5.7.1 <admin@peern.pw>: Sender address rejected: not logged in {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "meta": {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "component": "mail",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "err": "Error: Can't send mail - all recipients were rejected: 553 5.7.1 <admin@peern.pw>: Sender address rejected: not logged in\n    at SMTPConnection._formatError (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)\n    at SMTPConnection._actionRCPT (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1425:28)\n    at SMTPConnection._responseActions.push.str (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1378:30)\n    at SMTPConnection._processResponse (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)\n    at SMTPConnection._onData (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)\n    at Socket._socket.on.chunk (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "tnx": "transport",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "action": "send"
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.315 error: Cannot execute job 2. {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "meta": {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:     "err": "Error: Can't send mail - all recipients were rejected: 553 5.7.1 <admin@peern.pw>: Sender address rejected: not logged in\n    at SMTPConnection._formatError (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)\n    at SMTPConnection._actionRCPT (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1425:28)\n    at SMTPConnection._responseActions.push.str (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:1378:30)\n    at SMTPConnection._processResponse (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)\n    at SMTPConnection._onData (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)\n    at Socket._socket.on.chunk (/var/www/peertube/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)"
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
juil. 25 02:16:36 yh.peern.pw peertube[3184]: [peern.pw:443] 2018-07-25 02:16:36.322 info: Connection closed {
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "component": "smtp-connection",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "sid": "f1DXr5ygaaE",
juil. 25 02:16:36 yh.peern.pw peertube[3184]:   "tnx": "network"
juil. 25 02:16:36 yh.peern.pw peertube[3184]: }
`
I also use the https://ports.yunohost.org/?host=peern.pw&eport=&submit=Check and this reveal me that the port 465 is closed. I try to set it up by the firewall in the YNH but this not work.

I'm using the OVH repository , use a Let's Encrypt certificate and config the my domain name as it's said in the YNH.

Thank you

**Comment by anmol26s** [comment]
Your password is : wocafezedefutapo 
This can be seen. You can reinstall the app again.
Maybe try to install with root. Root can be logged in from admin interface.
By the way which OVH VPS you are using? Some people are having trouble to install Peertube on OVH.

**Comment by filmaidykai** [comment]
tell me how you just install peertube lol in to this ovh?... second thing you can use I forgot my password thing that maybe helps for you

**Comment by anmol26s** [comment]
@maitorouge 

Is the problem solved?

**Comment by anmol26s** [comment]
I have done a repo for the ovh server. You will need to do manual steps. 
see here in the reop branch of peertube. It has instruction for doing it.
https://github.com/YunoHost-Apps/peertube_ynh/tree/ovh_fix

**Comment by liberodark** [comment]
For me work on 1.0.0 Final !
But i cant receive email on install have install on debug mode for see password

**Comment by anmol26s** [comment]
@liberodark 
The mail issue will be common for all the apps. So you can open a post of forum.yunohost.org.
You can test the email on cmd and see what is the error.

`$ echo "Test message" | /usr/bin/bsd-mailx -a "Content-Type: text/plain; charset=UTF-8" -s "Test body message" "admin@domail.tld"`

If this don't work try:

`$ echo "Test message" | /usr/bin/mail.mailutils -a "Content-Type: text/plain; charset=UTF-8" -s "Test body message" "admin@domail.tld"`

**Comment by supermamie** [comment]
Just for info, I have the same problem.

I previously installed peertube during the beta phase and didn't understood why my app did not update, so I just uninstalled it and reinstalled.

And then, I remembered that I had a problem with password last time (but no idea on how I fixed it).

I tried to parse the logs, found the password, but I am unable to log in.

I tried the 1st line to send mail you provided, but /usr/bin/bsd-mailx was not found, so I tried with just "mail" and it worked fine.

I am hosted at home on a small computer so I should not have too specific limitations.

I have no idea on why the password in the logs does not work, so I think I'll just uninstall peertube for now :(

**Comment by anmol26s** [comment]
@supermamie 
You can change the admin password by:
`$ cd /var/www/peertube && NODE_CONFIG_DIR="/var/www/peertube/config/" NODE_ENV=production npm run reset-password -- -u root
`

Please open a post in the yunohost https://forum.yunohost.org as this mail issue is not effects all apps and not just peertube.
You can also open issue on the experimental helper reop https://github.com/YunoHost-Apps/Experimental_helpers

**Comment by jodumont** [comment]
@anmol26s 

as root
`$ cd /var/www/peertube && NODE_CONFIG_DIR="/var/www/peertube/config/" NODE_ENV=production npm run reset-password -- -u root `

return : `bash: npm: command not found`

but `whereis npm` return `npm: /opt/node_n/bin/npm`

**Comment by yalh76** [comment]
Sending mail issue is now solved, you can upgrade peertube_ynh using `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`

**Comment by arnaudbagnis** [comment]
Bonjour j'ai toujours le même soucis 

> @liberodark
> Le problème de messagerie sera commun à toutes les applications. Vous pouvez donc ouvrir un message sur forum.yunohost.org.
> Vous pouvez tester l'e-mail sur cmd et voir quelle est l'erreur.
> 
> `$ echo "Test message" | /usr/bin/bsd-mailx -a "Content-Type: text/plain; charset=UTF-8" -s "Test body message" "admin@domail.tld"`
> 
> Si cela ne fonctionne pas, essayez:
> 
> `$ echo "Test message" | /usr/bin/mail.mailutils -a "Content-Type: text/plain; charset=UTF-8" -s "Test body message" "admin@domail.tld"`

par contre cette commande marche

**Comment by arnaudbagnis** [comment]
mail.log 
`Dec  7 18:48:23 lapesto postfix/smtpd[14850]: connect from localhost[127.0.0.1]
Dec  7 18:48:23 lapesto postfix/smtpd[14850]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 553 5.7.1 <webmaster@tv.lapesto.fr>: Sender address rejected: not logged in; from=<we$
Dec  7 18:48:23 lapesto postfix/smtpd[14850]: lost connection after RCPT from localhost[127.0.0.1]
Dec  7 18:48:23 lapesto postfix/smtpd[14850]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=0/1 commands=2/3`

**Comment by yalh76** [comment]
did the email address `webmaster@tv.lapesto.fr` exist on your YunoHost ?

**Comment by gnouts** [comment]
Idem
Peertube doesn't send anything. It's an old install (I can't remember how I got the root password)
But when I create a user and force resend password reset link, it doesn't work.
The email exists. My server is able to send mail (cronjob and mail.mailutils send mails)

This is the log on startup from journalctl : 
```
Mar 12 12:51:07 alttube.fr peertube[13161]: > node dist/server
Mar 12 12:51:09 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:09.421 warn: Redundancy directory should be different than the videos folder.
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.166 info: Database peertube_peertube is ready.
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.477 info: Using localhost:25 as SMTP server.
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.483 info: Testing SMTP server...
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.518 info: Connection established to 127.0.0.1:25 {
Mar 12 12:51:10 alttube.fr peertube[13161]:   "component": "smtp-connection",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "sid": "FViDWNQvx8k",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "tnx": "network",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "localAddress": "127.0.0.1",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "localPort": 38774,
Mar 12 12:51:10 alttube.fr peertube[13161]:   "remoteAddress": "127.0.0.1",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "remotePort": 25
Mar 12 12:51:10 alttube.fr peertube[13161]: }
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.561 info: Successfully connected to SMTP server.
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.570 info: Cleaning HTML cache.
Mar 12 12:51:10 alttube.fr peertube[13161]: [alttube.fr:443] 2020-03-12 12:51:10.594 info: Connection closed {
Mar 12 12:51:10 alttube.fr peertube[13161]:   "component": "smtp-connection",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "sid": "FViDWNQvx8k",
Mar 12 12:51:10 alttube.fr peertube[13161]:   "tnx": "network"
Mar 12 12:51:10 alttube.fr peertube[13161]: }
```

(I'm using OVH branch)

**Comment by yalh76** [comment]
There is an ongoing PR that should definitively solve that issue: https://github.com/YunoHost/yunohost/pull/882

**Comment by arnaudbagnis** [comment]
When do you think it will be available?
If it's just simple orders, I can do them manually

**Comment by yalh76** [comment]
Won't be fixed soon, so better for now change it manually

**Comment by arnaudbagnis** [comment]
> Won't be fixed soon, so better for now change it manually

What manipulation to do to change it manually? I don't think I understand too much

**Comment by gnouts** [comment]
Apply the PR changes manually. The changes can be viewed there : https://github.com/YunoHost/yunohost/pull/882/files
It's 2 lines to add in data/templates/postfix/main.cf
I guess a restart is required then.
