### ISSUE TITLE
Peertube 5.1 released !

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/peertube_ynh#371]
Peertube 5.1 released ! https://github.com/Chocobozzz/PeerTube/releases/tag/v5.1.0
And thanks for ALL the work done to allow having Peertube as an Yunohost apps !

**Comment by fflorent** [comment]
FWIW, there is a github workflow that is run every day at 6 am to create a pull-request when a new version is out.

You don't have to worry about the creation of this kind of issue. However you are welcome to watch for the next PR and bring changes to production.yaml or to nginx configuration if some are required.

**Comment by tituspijean** [comment]
Fixed by #374
