### ISSUE TITLE
Livechat plugin v6.0.0+ do not require prosody_ynh anymore

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/peertube_ynh#375]
Direct feedback from @JohnXLivingston during the JDLL:

Since its version [v6.0.0](https://github.com/JohnXLivingston/peertube-plugin-livechat/releases/tag/v6.0.0), the chat plugin relies on Prosody AppImage, which means we don't need prosody_ynh anymore, thus not disabling Metronome.

This is valid for all architectures except ARM, he's working on it.

**Comment by JohnXLivingston** [comment]
Thanks @tituspijean :)

**Comment by JohnXLivingston** [comment]
I'm going to release the v7.0.0 for the chat plugin. It should be compatible with ARM64.
If someone using such CPU can confirm that it works after:
- updating the plugin to v7.0.0
- disabling the settings «use system prosody» in the plugin settings

The v7.0.0 should be available in a few hours.
