### ISSUE TITLE
Borg backup "fails" for peertube - thumbnails no such file or directory

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/peertube_ynh#377]
### Describe the bug

I'm using [borg_ynh](https://github.com/YunoHost-Apps/borg_ynh) to backup my server. Backups are always marked as "failed" for peertube app. Actually, the backup and restoration is working for peertube, it's just marked as failed because of some thumbnails files that are not found (see logs below).
Actually, same issue with a backup made by the API, backup fails.
The backup has about 30 GB of data.

### Context

- Hardware: *Old laptop*
- YunoHost version: 11.1.19
- I have access to my server: *Through SSH and through the webadmin and direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: *peertube 5.1.0~ynh1*

### Steps to reproduce

Make a backup of peertube app using yunohost's backup.

### Expected behavior

Backup success.

### Logs

Backup in webadmin : https://paste.yunohost.org/raw/awoquwuyeg
`FileNotFoundError: [Errno 2] No such file or directory: '/home/yunohost.app/peertube/storage/thumbnails/3bfa2f49-fef3-4470-b6aa-48f4f260a5ab.jpg'`

Backup with borg : https://paste.yunohost.org/raw/irulusiqok
`2023-05-20 08:43:30,038: DEBUG - [2023-05-20_07:28:06] apps/peertube/backup/home/yunohost.app/peertube/storage/thumbnails/fd320be9-fd42-4411-856d-f204ce9e1a22.jpg: stat: [Errno 2] No such file or directory: 'apps/peertube/backup/home/yunohost.app/peertube/storage/thumbnails/fd320be9-fd42-4411-856d-f204ce9e1a22.jpg'`

**Comment by tio-trom** [comment]
Weird. Same here:
```

2023-10-10 02:35:51,000: DEBUG - [2023-10-10_00:58:08] apps/peertube/backup/home/yunohost.app/peertube/storage/thumbnails/8cc82796-465e-4679-9403-31d31ae67e99.jpg: stat: [Errno 2] No such file or directory: 'apps/peertube/backup/home/yunohost.app/peertube/storage/thumbnails/8cc82796-465e-4679-9403-31d31ae67e99.jpg'
2023-10-10 02:35:52,062: ERROR - Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 298, in hook_callback
    hook_return = hook_exec(
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 410, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app

```

But it seems the backups are going through...

**Comment by ericgaspar** [comment]
closing with #414
