### ISSUE TITLE
Fail to install peertube_ynh on Yunohost 3.1

### ISSUE THREAD

**Issue by partok** [YunoHost-Apps/peertube_ynh#38]
Hi,
I have a fresh Yunohost 3.1 running on a proxmox server (as container).
When trying to install peertube_ynh, I get these messages and then the installation fails:
WARNING psql: could not connect to server: No such file or directory
WARNING   Is the server running locally and accepting
WARNING   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
See the [full log](http://sebsauvage.net/paste/?05104f7d59e3e95c#9HHKLMs+ETftnQ69ga4m+CX4FSltpHYUp9aVans3z4U=).
Thanks.

**Comment by anmol26s** [comment]
Sorry for the late reply. I was not well.
Can you test if PostgreSQL is installed? If yes what is the version of PostgreSQL?

**Comment by anmol26s** [comment]
Hi @partok 

Can you do? 

`$ pg_createcluster 9.6 main --start`

 then:

`$ /etc/init.d/postgresql start
`
And tell me the output please.

**Comment by partok** [comment]
Sorry for the delay and thank you for your help.
I can only try tomorrow.

**Comment by anmol26s** [comment]
No problem. Please try it when ever you can.

**Comment by partok** [comment]
It works a little better but the installation still fails.
Thanks anyway.


root@xxxxx:~# pg_createcluster 9.6 main --start
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error: The locale requested by the environment is invalid:
  LANG: C
  LC_ALL: en_US.UTF-8
  
root@xxxxx:~# /etc/init.d/postgresql start
[ ok ] Starting postgresql (via systemctl): postgresql.service.

root@xxxxx:~# yunohost app install --debug https://github.com/YunoHost-Apps/peertube_ynh

[...]
106213 DEBUG + ynh_psql_test_if_first_run
106213 DEBUG + '[' -f /etc/yunohost/psql ']'
106213 DEBUG + echo 'PostgreSQL is already installed, no need to create master password'
106214 DEBUG PostgreSQL is already installed, no need to create master password
106214 DEBUG + ynh_psql_create_user peertube L7O5O1M7wBFTibRrJfPh5jFYhCNPi5
106214 DEBUG + user=peertube
106214 DEBUG + pwd=L7O5O1M7wBFTibRrJfPh5jFYhCNPi5
106214 DEBUG + sudo --login --user=postgres psql '-cCREATE USER peertube WITH PASSWORD '\''L7O5O1M7wBFTibRrJfPh5jFYhCNPi5'\''' postgres
106314 WARNING -bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
106314 WARNING perl: warning: Setting locale failed.
106315 WARNING perl: warning: Please check that your locale settings:
106315 WARNING  LANGUAGE = (unset),
106315 WARNING  LC_ALL = "en_US.UTF-8",
106315 WARNING  LANG = "C"
106315 WARNING     are supported and installed on your system.
106315 WARNING perl: warning: Falling back to the standard locale ("C").
106315 WARNING /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
106416 DEBUG + ynh_exit_properly
106416 WARNING psql: could not connect to server: No such file or directory
106416 DEBUG + local exit_code=2
106416 WARNING  Is the server running locally and accepting
106416 DEBUG + '[' 2 -eq 0 ']'
106416 WARNING  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
106416 DEBUG + trap '' EXIT
106417 WARNING !!
106417 DEBUG + set +eu
106417 WARNING   peertube's script has encountered an error. Its execution was cancelled.
106417 DEBUG + echo -e '!!\n  peertube'\''s script has encountered an error. Its execution was cancelled.\n!!'
106417 WARNING !!
[...]

**Comment by anmol26s** [comment]
Remove the PostgreSQL and let the app install it again for you. Check if other installed apps uses postgresql,but  I think no other installed app would be using it as the postgresql database is not getting created and this should happen for all the apps which are using postgresql will give same error as far as I can understand. 

$ apt-get remove postgresql

**Comment by partok** [comment]
Nearly same error:

73324 DEBUG + ynh_psql_test_if_first_run
73324 WARNING -bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
73324 DEBUG + '[' -f /etc/yunohost/psql ']'
73324 WARNING perl: warning: Setting locale failed.
73324 DEBUG + echo 'PostgreSQL is already installed, no need to create master password'
73324 WARNING perl: warning: Please check that your locale settings:
73324 DEBUG PostgreSQL is already installed, no need to create master password
73325 WARNING   LANGUAGE = (unset),
73325 DEBUG + ynh_psql_create_user peertube BzHbMOhtwrAHSxd43dRCWWWzxD3kVQ
73325 WARNING   LC_ALL = "en_US.UTF-8",
73325 DEBUG + user=peertube
73325 WARNING   LANG = "C"
73325 DEBUG + pwd=BzHbMOhtwrAHSxd43dRCWWWzxD3kVQ
73325 WARNING     are supported and installed on your system.
73325 DEBUG + sudo --login --user=postgres psql '-cCREATE USER peertube WITH PASSWORD'\''BzHbMOhtwrAHSxd43dRCWWWzxD3kVQ'\''' postgres
73325 WARNING perl: warning: Falling back to the standard locale ("C").
73325 WARNING /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
73426 DEBUG + ynh_exit_properly
73426 WARNING psql: could not connect to server: No such file or directory
73426 DEBUG + local exit_code=2
73426 WARNING   Is the server running locally and accepting
73426 DEBUG + '[' 2 -eq 0 ']'
73426 WARNING   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
73427 DEBUG + trap '' EXIT
73427 WARNING !!
73427 DEBUG + set +eu
73427 WARNING   peertube's script has encountered an error. Its execution was cancelled.
73427 DEBUG + echo -e '!!\n  peertube'\''s script has encountered an error. Its execution was cancelled.\n!!'
73427 WARNING !!

**Comment by anmol26s** [comment]
I think its locale error.

Do
```
echo "LC_ALL=en_US.UTF-8" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8
```
And try to install the package again. I hope it works this time.

**Comment by partok** [comment]
It didn't work (but less annoying warnings).

I tried this:
`sudo apt-get remove --purge postgresql*
sudo apt-get install postgresql`
and the installation went fine!

Many thanks for your help anmol26s.

**Comment by anmol26s** [comment]
Thanks for the solution. Many have apps have similar problems because of this error. So remove postgresql and installing it again would be the solution for them.

Can we close the issue ?
