### ISSUE TITLE
Peertube (transcoding) runners as a Yunohost package ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/peertube_ynh#381]
As of version 5.2, Peertube now includes a mechanism that allows video transcoding to be done in another server: remote runner (https://docs.joinpeertube.org/admin/remote-runners).

Installing it seems quite simple (https://docs.joinpeertube.org/maintain/tools#peertube-runner), but might be a trouble in a Yunohost installation in case of conflicts.
I'm unsure if a classical Peertube instance can provide remote runners. But it might be a bit overkill to install a whole instance on a server that will only provide computing power.

Should we make it a separate package ?
Include it in this one ?

What do you think ?

Thank you.

**Comment by lapineige** [comment]
Work started here : https://github.com/YunoHost-Apps/peertube_remote_runner_ynh

**Comment by tio-trom** [comment]
> But it might be a bit overkill to install a whole instance on a server that will only provide computing power.

It is not because people may already have YNH instances and want to use the servers as transcoders for other servers. Like I have 2 YNH servers. The Peertube instance is on one, but I'd like to use my second YNH server as a runner too. Thank you for doing this!
