### ISSUE TITLE
Adapt the package to work with the runners

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/peertube_ynh#382]
Please follow our discussion here https://github.com/Chocobozzz/PeerTube/issues/5849 - it seems that with the new "runners" feature the nginx file must be adapted.

**Comment by lapineige** [comment]
I will also link this : #381

**Comment by lapineige** [comment]
Also the upstream issue was closed https://github.com/Chocobozzz/PeerTube/issues/5849#issuecomment-1607300859 because it should be fixed on Peertube side in a future version.

**Comment by tio-trom** [comment]
> Also the upstream issue was closed [Chocobozzz/PeerTube#5849 (comment)](https://github.com/Chocobozzz/PeerTube/issues/5849#issuecomment-1607300859) because it should be fixed on Peertube side in a future version.

Yes some things, but we need to add the runner to the production file https://github.com/Chocobozzz/PeerTube/issues/5849#issuecomment-1605915295 and add them to nginx too https://github.com/Chocobozzz/PeerTube/issues/5849#issuecomment-1605773113

**Comment by lapineige** [comment]
For your information using #381 I successfully tried it and runners work out of the box :D

**Comment by tio-trom** [comment]
> For your information using #381 I successfully tried it and runners work out of the box :D

Yes but did you try with big files? Because that was the issue really.

**Comment by lapineige** [comment]
:bulb:
Thanks, I didn't understand this before !

So yes, this is an issue with the Peertube app.
