### ISSUE TITLE
Unable to install on YunoHost

### ISSUE THREAD

**Issue by Sc0rp007** [YunoHost-Apps/peertube_ynh#386]
Bonjour, 
Il m'est impossible de faire l'installation de Peertube sur mon YunoHost. Je vous partage le journal pour vous permettre d'y jeter un œil.
Le problème viendrait du plugin LDAP... étant novice sur le sujet j'aurais besoin de votre aide !! Merci par avance...

---
Hello I can't install Peertube on my YunoHost. I am sharing the newspaper with you so you can take a look at it. The problem would come from the LDAP plugin... Being a novice on the subject I would need your help !! Thank you in advance...
---
lien journal :
https://paste.yunohost.org/raw/ukidiwugim

**Comment by genma** [comment]
J'ai eu le même soucis, résolu comme indiqué dans les logs par une mise à jour de npm
Depuis une connexion sur le serveur (en ssh), avec un utilisateur admin, on lance la commande de mise à jour de Npm, une version plus récente étant nécessaire pour le plugin. La commande : 
# npm install -g npm

**Comment by tomtoom1978** [comment]
De mon coté toujours impossible d'installer la mise a jour, ou même une installation fraiche
malgré la maj npm en 10.2.4

j'ai le message suivant: (qui indique que npm n'est pas a jour )
Mais j'ai  npj -v qui indique bien en 10.2.4

Info: DEBUG - npm notice
Info: DEBUG - npm notice New major version of npm available! 8.19.4 -> 10.2.4
Info: DEBUG - npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
Info: DEBUG - npm notice Run `npm install -g npm@10.2.4` to update!

**Comment by ericgaspar** [comment]
fixed with #414
