### ISSUE TITLE
YunoHost and Peertube

### ISSUE THREAD

**Issue by Celan68** [YunoHost-Apps/peertube_ynh#387]
Hi, 

I can't connect to Peertube administration. I have tried all possible identifiers. 
I installed the instance from the Yunohost package and use a VPS with Debian 11. 
Thanks for any help. 

Mario

**Comment by Globulle** [comment]
Hi, is it still possible to install Peertube on YunoHost? I don't see it in the app catalog of the 11.2 version.

**Comment by Celan68** [comment]
Yes, it is. I did it and it works well.

**Comment by Globulle** [comment]
Version 5.2.1~ynh1 on YunoHost 11.2.5 ? It is labelled « broken » with important installation warning.

**Comment by Celan68** [comment]
I know, but you need to take the right security measures to protect your instance, depending on your installation (vps, raspberry, nas, docker, etc.). Also remember to take snapshots regularly. Finally, use the github link to install the instance, not the yunohost self-install button. Bye.
