### ISSUE TITLE
Peertube cassé, restauration sauvegarde impossible, mais J'ai trouvé une solution

### ISSUE THREAD

**Issue by tomtoom1978** [YunoHost-Apps/peertube_ynh#394]
**Petite explication avant la solution....**
Depuis quelque semaine impossible de mettre a jour peertube vers la 5.2.1, c’était pas grave je suis resté en 5.2.0.
Mais avant hier j'ai testé encore et la maj à fait planté complètement l'instance PeerTube. Yunohost lui n'avait pas de problèmes.
Et là le drame, la sauvegarde ne permet pas la réinstallation... plantage systématique.... même avec une sauvegarde plus ancienne.
Bref j'efface complètement peertube et lance l'installation d'un nouveau peertube... et la impossible d'installer...

**J'ai donc fait la procédure de migration pour réinstaller mon instance à la date de la sauvegarde:**
https://docs.joinpeertube.org/maintain/migration

Voici vite fait ma démarche, c'est sûrement imparfait, j'ai tâtonné et je l'écris de mémoire, mais ça peut être une piste pour certains d'entre vous.

1. copier le repertoire des données
2. copier la partie config
3. dumper la DB de postgresql en trouvant le pass de la db dans la partie config
4. j'ai effacé le répertoire peertube qui était dans yunohost.app (qui ne voulaient pas partir malgré la désinstallation) - cela faisait planté la nouvelle installation vierge visiblement.
5. Reinstallation vierge de peertube avec le même domain
6. je stop peertube
7. Reinjection de la DB
8. copier des fichiers de données
9. Copie les fichiers de config
10. ajustement du mot de passe de la DB dans le fichier de config (récupéré dans le nouveau fichier de config)

Courage, si vous avez une sauvegarde rien n'est perdu !!!!

**Comment by lapineige** [comment]
> Bref j'efface complètement peertube et lance l'installation d'un nouveau peertube... et la impossible d'installer...

#401 
C'est peut-être ça le problème.
As-tu des journaux d'une installation erronée ?

**Comment by MyNameIsTroll** [comment]
Voilà mes logs apres avoir tenté une désinstallation puis une réinstallation de l'app suite a la mise a jour qui n'a pas fonctionné:  
https://paste.yunohost.org/raw/odururayip

**Comment by lapineige** [comment]
```
DEBUG - + sudo -u peertube env PATH=/opt/node_n/n/versions/node/16/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin yarn install --production --pure-lockfile
DEBUG - yarn install v1.22.19
DEBUG - [1/5] Validating package.json...
DEBUG - error peertube@5.2.1: The engine "node" is incompatible with this module. Expected version ">=16.x". Got "12.22.12"
DEBUG - error Found incompatible module.
DEBUG - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

That is very strange…

**Comment by lapineige** [comment]
> j'ai effacé le répertoire peertube qui était dans yunohost.app (qui ne voulaient pas partir malgré la désinstallation) 

Il n'est jamais effacé à la désinstallation, car il contient les vidéos. Sinon, une mise à jour ratée supprimerait toutes les vidéos…

**Comment by lapineige** [comment]
@MyNameIsTroll does a fresh install of this PR https://github.com/YunoHost-Apps/peertube_ynh/pull/408 work on your side ?

**Comment by MyNameIsTroll** [comment]
@lapineige je ne sais pas comment faire pour tester une PR 😅

**Comment by lapineige** [comment]
`yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh/tree/testing-old` (éventuellement avec l'option `--force` si le numéro de version est le même, par exemple pour installer une nouvelle version de la PR en question)
