### ISSUE TITLE
database access authentication failed

### ISSUE THREAD

**Issue by CptCurk** [YunoHost-Apps/peertube_ynh#396]
### Describe the bug

Can't connect to the database using `psql peertube`.
Ask for password, enter the root user password (the one sended by mail). 

### Context

- Hardware: * Raspberry Pi at home*
- YunoHost version: 11.2.8.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

basicly, 

I don't know what's this password. When is it created and from what does that refer ?  I guess that's this database ?

database:
  hostname: 'localhost'
  port: 5432
  ssl: false
  suffix: '___APP__'
  username: '__DB_USER__'
  password: '__DB_PWD__'
  pool:
    max: 5

My purpose is just doing that : https://github.com/Chocobozzz/PeerTube/issues/870
DELETE FROM actor WHERE "preferredUsername" = '...' and "serverId" is null;

Thank you !

**Comment by tomtoom1978** [comment]
I think the password is somewhere inside the config file, you can find there:
/var/www/peertube/config

**Comment by CptCurk** [comment]
thank you for answer ! 
The config file you're speaking about is the production.yaml ?
