### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/peertube_ynh#4]
Hi,

Thanks for creating this app for YNH ! I tried to install the current version on my system (ARM) : 

yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7

It failed. 
I tried twice, and put the --verbose argument the second time. Here are the logs : 

https://paste.yunohost.org/dewosexave.sql

Thanks for your help

**Comment by rigelk** [comment]
hi @mokas01 

It's to be expected since the current `master` branch fetches upstream and expect a consistent hash. I fix it in #3, so you might start using it as soon as it is merged (or by cloning and checking out the PR).

**Comment by mokas01** [comment]
Great, thank you for your work

**Comment by anmol26s** [comment]
@mokas01 
You can try the testing branch https://github.com/YunoHost-Apps/peertube_ynh/tree/testing
