### ISSUE TITLE
install fail : The method driver /usr/lib/apt/methods/https could not be found

### ISSUE THREAD

**Issue by Olm-e** [YunoHost-Apps/peertube_ynh#41]
new yunohost x86 install and trying to install peertube from graphical interface result in error
same with command line : 
error : The method driver /usr/lib/apt/methods/https could not be found

solution : 
sudo apt-get install apt-transport-https

**Comment by anmol26s** [comment]
Are you running the Yunohost on vps or on home and can you also tell the config?
Can you tell the Yunohost version?
`$ yunohost -v`
After installing `apt-transport-https` the installation was successful?

**Comment by Olm-e** [comment]
it's on a home install on a old pc, with ynh image v 3.2 and yes after adding apt-transport-https it works ;)

**Comment by anmol26s** [comment]
I will add this dependency on the next PR. 
Thanks for reporting.

**Comment by anmol26s** [comment]
This issue has been fixed with the merge of the latest PR into master branch.
Thanks for reporting the issue.

**Comment by webxI23** [comment]
I had to install apt-transport-https manually on that version.

yunohost: 
  repo: stable
  version: 3.3.3
yunohost-admin: 
  repo: stable
  version: 3.3.1
moulinette: 
  repo: stable
  version: 3.3.1
ssowat: 
  repo: stable
  version: 3.3.2

Thanks
