### ISSUE TITLE
EACCES: permission denied, stat '/var/log/peertube/peertube.log'

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/peertube_ynh#431]
Hi, I tried to install peertube on a VM and it fails.

I feel like the meaningful error is:
Error: EACCES: permission denied, stat '/var/log/peertube/peertube.log

Here is the full log:
https://paste.yunohost.org/raw/ivaqapayat

any idea on how to solve that?

**Comment by Jibec** [comment]
I tried with testing branch since I saw the PR https://github.com/YunoHost-Apps/peertube_ynh/pull/430 related to logs, but the error is the same:

https://paste.yunohost.org/raw/vadovivaco

**Comment by ericgaspar** [comment]
fixed with https://github.com/YunoHost-Apps/peertube_ynh/pull/430

**Comment by fflorent** [comment]
Wait @ericgaspar 

[Quoting](https://github.com/YunoHost-Apps/peertube_ynh/pull/430#issuecomment-2053978906) @tituspijean:
> This was an attempt to fix https://github.com/YunoHost-Apps/peertube_ynh/issues/431, but Jibec reported that it does not solve the issue. :/
