### ISSUE TITLE
Upgrade from 6.0.3~ynh1 to 6.0.4~ynh1 fails bc of ldap plugin

### ISSUE THREAD

**Issue by yodahome** [YunoHost-Apps/peertube_ynh#435]
### Describe the bug

I tried upgrading my PeerTube 6.0.3 to the latest version (once via web ui, twice via CLI), but it failed with the attached errors on screen and in the log attached. Apparently it's an error when installing the ldap plugin, I'm not sure what the problem is there though.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.11.3
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: 6.0.3~ynh1

### Steps to reproduce

shell commands:
sudo yunohost tools upgrade apps
sudo yunohost app upgrade peertube

### Expected behavior

Was expecting the app to be upgraded to the latest version.

### Logs

https://paste.yunohost.org/raw/butudoxizi

**Comment by Chocobozzz** [comment]
Hi,

Have you the `peertube-plugin-transcription` plugin installed? If yes try to uninstall it before the upgrade

**Comment by yodahome** [comment]
> Hi,
> 
> Have you the `peertube-plugin-transcription` plugin installed? If yes try to uninstall it before the upgrade

Yes, indeed I did and after uninstalling the plugin the update went through. Thanks for the hint!
