### ISSUE TITLE
Oneprovider root access 

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#44]
Hey guys I just ordered oneprivider one of them vps so install yunohost app and peertube as well everything like and fine but when I wanna share iframe link its not working so I found a solution yunohost forum what I have to do just 

 edit the main domain nginx file to remove X-frame header.

$ nano /etc/nginx/conf.d/tube.ziuri.me.conf

Remove
add_header X-Frame-Options "SAMEORIGIN";  

But there is the problem they dont give a root access i was trying to do that over ftp nothing they gave me error Im not root guy or something like that so just question maybe possible to do that via terminal?  If yes can someone explain how to do that

Thanks

**Comment by anmol26s** [comment]
$ sudo nano /etc/nginx/conf.d/tube.ziuri.me.conf

**Comment by anmol26s** [comment]
Is the issue resolved?

**Comment by filmaidykai** [comment]
Yeap its working fine thanks
