### ISSUE TITLE
Redis version is obsolete

### ISSUE THREAD

**Issue by magostinelli** [YunoHost-Apps/peertube_ynh#448]
### Describe the bug

Redis is not the recommended version.

### Context
YunoHost version: 11.2.27
Peertube version: 6.2.1~ynh1
Os: Debian 11.10

### Steps to reproduce
journalctl -u peertube.service

### Expected behavior
Use a Redis recommended version

### Logs
It is highly recommended to use a minimum Redis version of 6.2.0
Current: 6.0.16

**Comment by fflorent** [comment]
This should be fixed with the migration to Yunohost Bookworm:
https://packages.debian.org/search?keywords=redis

**Comment by ericgaspar** [comment]
#462 should fix the issue
