### ISSUE TITLE
Questions - after sync delete original files

### ISSUE THREAD

**Issue by chefblogger** [YunoHost-Apps/peertube_ynh#457]
i have synchronised my peertube with my youtube - it worked great. 

on peertube i reduce the videos to 720p - can i delete the original files somewhere to free up space - if so how? 

Unfortunately I can't find any instructions or path to the folder with the original videos

thank you for your answers :)

**Comment by JohnXLivingston** [comment]
For question like this, that only concern the app and not Yunohost directly, you better ask on the app platforms.
For example, for Peertube, you have this forum: https://framacolibri.org/c/peertube/38
