### ISSUE TITLE
System can no longer find videos

### ISSUE THREAD

**Issue by stealthhq** [YunoHost-Apps/peertube_ynh#63]
My instance is stoptrackingus.tv.  Installed this past weekend and 4 gigs of videos were playing correctly.  Today they are not.  I think some how the folder for videos were changed on the server after uploading the most recent videos today with a url.  The console show the following errors:  

[Report Only] Refused to load media from 'blob:https://stoptrackingus.tv/f23d8178-af3c-46b6-b971-017870481059' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

/static/webseed/f8042d55-408b-4399-be9b-951baeabcb40-720.mp4:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by rigelk** [comment]
The CSP error can be safely ignored, as it is not enforced. However the 404 on your files shows that the file is not present anymore at its expected place, if not at all.

**Comment by stealthhq** [comment]
Well my videos are still in /storage/videos so if anyone can think of any reason this happened let me know.  It reports videos not found right after "successful" uploads. 5TB server I'm trying to get up and running for a large public installation.
