### ISSUE TITLE
app install in /video even when choosing domain root as installation candidate

### ISSUE THREAD

**Issue by stealthhq** [YunoHost-Apps/peertube_ynh#66]
Is there a way to redirect to the /video so that when someone types in the base domain it opens peertube.

Right now if you go to stoptrackingus.tv you get redirected to the yunohost admin domain.  Looking at the nginx conf for the new install it states location /yunohost/admin.  

I am guessing for me the install is not creating the correct nginx conf.

**Comment by anmol26s** [comment]
I would like to see files inside 
1. /etc/nginx/conf.d/stoptrackingus.tv.d/
2. File /etc/ssowat/conf.json.persistent
3. File /etc/yunohost/apps/peertube/settings.yml (with important details removed, like db password)

And it would be good if you can tell how you have configured DNS for stoptrackingus.tv.

Normally you get redirected to admin interface if SSO don't find any app on that domain. But as there is peertube installed on stoptrackingus.tv it should not redirect to admin interface. Have you tried other app no other domain?

**Comment by stealthhq** [comment]
I think I found the issue the file /etc/ssowat/conf.json.persistent was automatically redirecting any domain that ended with / to yunohost admin. I just made and edit and rebooted.  It now works as expected.  Weird thing is it has been doing this for the last 3 fresh installs with new vps and ip.

**Comment by anmol26s** [comment]
If you have manually not added this line in conf.json.persistent then you should open an issue with Yunohost.

Closing this.
