### ISSUE TITLE
Embedded video player not working

### ISSUE THREAD

**Issue by makotoworkshop** [YunoHost-Apps/peertube_ynh#67]
Hi !
Peertube 1.1.0, fresh updated by 
`sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/peertube_ynh peertube`

Got « peertube.makotoworkshop.org refused to connect. » instead the video player, when i used the html code Share > Embed, to embedded a local video, for example : 
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube.makotoworkshop.org/videos/embed/8d76f48d-45bc-453e-aebd-f378eca3dfa4" frameborder="0" allowfullscreen></iframe>`

« Funny thing » if i used the code from another instance for the same video, it's work :
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube1.olympe.online/videos/embed/8d76f48d-45bc-453e-aebd-f378eca3dfa4" frameborder="0" allowfullscreen></iframe>`

Error.log : 
```2019/01/01 20:08:02 [error] 21193#21193: *26106 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: peertube.makotoworkshop.org, request: "GET /videos/embed/8d
76f48d-45bc-453e-aebd-f378eca3dfa4 HTTP/2.0", upstream: "http://127.0.0.1:9000/videos/embed/8d76f48d-45bc-453e-aebd-f378eca3dfa4", host: "peertube.makotoworkshop.org", referrer: "https://burogu.makotoworkshop.or
g/index.php?preview/makoto/e3a6b36562694e2ca67ca727e7155c40a0df0b50/2019/01/01/eolienne-axe-vertical-12" 
```

Don't know if it's linked, but got also many error like this : 
```
2019/01/01 20:08:25 [error] 21192#21192: *26167 connect() failed (111: Connection refused) while connecting to upstream, client: 94.237.44.206, server: peertube.makotoworkshop.org, request: "POST /inbox HTTP/1.1
", upstream: "http://127.0.0.1:9000/inbox", host: "peertube.makotoworkshop.org" 
```

**Comment by anmol26s** [comment]
Please do as described  and give feedback if it works.
1.     Go to /etc/nginx/conf.d/peertube.makotoworkshop.org.conf
2.     Remove this line add_header X-Frame-Options “SAMEORIGIN”;
3.     Restart nginx $ sudo service nginx restart.

**Comment by makotoworkshop** [comment]
As you propose, i commented the line :
`#    more_set_headers "X-Frame-Options : SAMEORIGIN"; `
And restart nginx
It's work !
Many Thanks ^^

Don't know why the upgrade have not update the nginx config file.
Maybe the Yunohost App update noticed that the config file have not been update because the file « have been modified manualy », like i've seen for another Yunohost apps update.
But when that happened, there is no way to examine the issue, like option to see diff, overwrite the config file, and so on, like i've seen with classic debian upgrade package.

**Comment by yalh76** [comment]
Feel free to reopen this issue if needed.

**Comment by makotoworkshop** [comment]
Hi !

I wrote this new message to report that,
Everythings work fine up to PeerTube v2.0.0, but since updated to 2.1.1, the same problem happened again.
Here example : 
https://peertube.makotoworkshop.org/videos/test-embed/1b6340b8-fd31-4c82-ad6e-b782958537ed
https://peertube.makotoworkshop.org/videos/embed/1b6340b8-fd31-4c82-ad6e-b782958537ed

I tried some things like : 

- I've restore a Yunohost backup to confirm that v2.0.0 work fine (and restore the v2.1.1)

- Add the ALLOWALL option, like i've see in other issues : 
```
nano /etc/nginx/conf.d/peertube.makotoworkshop.org.conf

#    more_set_headers "X-Frame-Options : SAMEORIGIN";
     more_set_headers "X-Frame-Options : ALLOWALL";
```
But with or without this line, same results, video embedded is not playable.

**Comment by makotoworkshop** [comment]
Don't know how it's happened… but after a while, since i wrote here, embed vidéos works again…
« C'est tombé en marche ! »

**Comment by kamazeuci** [comment]
this is not working for me... in fact, this line doesn't exist...

`#    more_set_headers "X-Frame-Options : SAMEORIGIN";`

any ideas?

**Comment by kamazeuci** [comment]
here is the solution: https://github.com/aymhce/collaboradocker_ynh/issues/17
I was using the wrong .conf file
