### ISSUE TITLE
Peertube removed after upgrade

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/peertube_ynh#68]
Hi ! I tried to upgrade peertube today, and it has just removed the app. Fortunately I had just one local video on it, it was just to test.
Here are the logs I found on admin page : https://plaf.fr/zerobin/?23b8d6a589192371#hjdE/xswN3KAbXHZTEI6ULdmHk38IHhdlFwjAI1XB7o=

**Comment by anmol26s** [comment]
Peertube should restore itself if the upgrade fails.

**Comment by yalh76** [comment]
Peertube_ynh has been upgraded, you can try to upgrade using `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`
