### ISSUE TITLE
 Subtitles won't upload and UI freeze

### ISSUE THREAD

**Issue by makotoworkshop** [YunoHost-Apps/peertube_ynh#70]
Same as this with Yunohost Version 1.1.0
https://github.com/Chocobozzz/PeerTube/issues/1501

But to correct this bug, i don't find the file _**video-caption-add-modal.component.ts**_ in _/var/www/peertube_ or _/home/yunohost.app/peertube_
https://github.com/Chocobozzz/PeerTube/blob/259dd796e6d93db8068ec47aac99a560f2818673/client/src/app/videos/%2Bvideo-edit/shared/video-caption-add-modal.component.ts

And i cannot check for update of peertube_ynh, because of this issue
https://forum.yunohost.org/t/mise-a-jour-yunohost-impossible/4641/10

**Comment by yalh76** [comment]
Hi @makotoworkshop 

Can you try to upgrade to last peertube_ynh version 1.21.1 and let us know if there is still a problem.

`yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`
