### ISSUE TITLE
Don't store videos on /var/www/peertube (small partition)

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/peertube_ynh#8]
I don't know if this is only on my yunohost install, but the partition is done so that /var is 2Go and most of the space available is on /home. So I ended up filling my /var with uploaded videos. I moved the videos folder to /home/peertube/videos and added a symbolic link : 

```
ls /var/www/peertube 
[snip]
lrwxrwxrwx   1 root     root       22 mars  22 21:29 videos -> /home/peertube/videos/
```

**Comment by anmol26s** [comment]
Its a very good suggestion. Planning  various basic structures beforehand would be better for updating and restoring the app too.

**Comment by anmol26s** [comment]
Now videos are stored in /home/yunohost.app/app/storage as you suggested.
