### ISSUE TITLE
Peertube manage follows

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#82]
Hey I just done fresh install for peertube and wanna fallow some instances but got pending status like on this screen [https://prnt.sc/myzzzl](url) maybe anyone know how accept it?

**Comment by yalh76** [comment]
Hi @filmaidykai 

Did the status goes fine now ?

**Comment by filmaidykai** [comment]
No everything the same for some is working fine for some showing scrap

**Comment by yalh76** [comment]
could you first upgrade using to the last version of peertube_ynh `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh` and let us know if it solved that issue

**Comment by filmaidykai** [comment]
So im already using 1.2.1 version

**Comment by yalh76** [comment]
Ok then, will wait the next upgrade, there are several 1.3.0 releases candidates

**Comment by filmaidykai** [comment]
Yea I saw it they done lot of new things I can't wait to try it lol

**Comment by yalh76** [comment]
just waiting the 1.3.0 final ^^

**Comment by filmaidykai** [comment]
I hope its will be soon because how i can see now they have problems with transcoding...second one  If you make playlist you cant share anywhere it like youtube have proper embed and much more things
