### ISSUE TITLE
Please consider using ynh_install_extra_repo

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/peertube_ynh#84]
Hi

We noticed that you use an extra repository for your app. Using extra repository without pinning it can have consequences.
Please consider using the experimental helper [ynh_install_extra_repo](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__2) to handle securely any extra repo.

If you encounter any problem using this helper, please open an issue on the repo.

**Comment by yalh76** [comment]
ynh_add_secure_repos__3 implemented in https://github.com/YunoHost-Apps/peertube_ynh/pull/85
