### ISSUE TITLE
change smtp config for peertube

### ISSUE THREAD

**Issue by aksildoescode** [YunoHost-Apps/peertube_ynh#87]
I juste install peertube with yunouhost on vps server and everything looks working fine but i peertube cannot send email. for admin email i get it from logs but need peertube to send email for forgotten user password or cotact page for example.
thanks

**Comment by yalh76** [comment]
Sending mail is now solved in the last update. Just tested.
You can update using `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`
