### ISSUE TITLE
Can't show iframes on other domains

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/peertube_ynh#97]
From @raphgilles https://github.com/YunoHost-Apps/peertube_ynh/issues/80#issuecomment-499290020

Oh ! And it's not the subject of this issue, but we must to comment the line 59 of the nginx .conf file :
`# more_set_headers "X-Frame-Options : SAMEORIGIN";`

If it's not commented, we can't show iframes on other domains.

**Comment by yalh76** [comment]
@raphgilles

You made this change on wich nginx conf file because there is no `more_set_headers "X-Frame-Options : SAMEORIGIN";` in peertube nginx.conf file

**Comment by raphgilles** [comment]
In `/etc/nginx/conf.d/domain.td.conf`

**Comment by yalh76** [comment]
Thanks, just fixed on https://github.com/YunoHost-Apps/peertube_ynh/commit/7e3d7ba45d4596d2172aa13aefc65413fffc06f7

I didn't comment the line but change to `X-Frame-Options : ALLOWALL`
